ACCE_CLEAR_ATTR_CONFIRM	Do you really want to clear bonuses?
ACCE_COMBINE_NEEDED_ITEMS	Required items
ARCTIC_DUNGEON	Ice Cave
ARTEFAKT_WINDOW_TITLE	Ancient Artifacts
ASLAN_BUFF_CHANGE_SEX	Change gender
ASLAN_BUFF_CHAT_INFO_NAME_IS_EMPTY	You must enter a name.
ASLAN_BUFF_EQUIPMENT	Equipment
ASLAN_BUFF_HOVER_EXP_INFO	Experience: %s / %s (%.2f%%)
ASLAN_BUFF_INPUT_NAME_TITLE	Enter Name
ASLAN_BUFF_SELECT_SKILL	Select Skill
ASLAN_BUFF_SKILLS	Skills
ASLAN_BUFF_SUMMON	Summon
ASLAN_BUFF_TITLE_CHANGE_NAME	Change Name
ASLAN_BUFF_TITLE_CREATE_BOARD	Helper Panel
ASLAN_BUFF_TITLE_LEARN_GRANDMASTER	Skill Training
ASLAN_BUFF_TITLE_MAIN_BOARD	Helper Panel
ASLAN_BUFF_UNSUMMON	Dismiss
AUTO_SHOUT_BUTTON	Auto shout (Call)
AUTO_SHOUT_INFO	Auto shout sending activated.
AUTO_SHOUT_INFO2	Auto shout sending deactivated.
AUTO_SHOUT_INFO3	Last shout message not found. Auto shout will start when you write something.
AUTOMATIC_SPINNING	Automatic spinning
AVAILABLE_MISSIONS	Available missions
AVERAGE_DAMAGE_DUNGEON_2	Emperor's Gorge
BATTLE_PASS_2	Daily tasks
BATTLE_PASS_3	Weekly tasks
BIGGER_STAR_CHANCE	|cFF63f282BIGGER CHANCE FOR FISHING STAR|h|r
BLEND_WINDOW_1	You didn't choose any elixir!
BLEND_WINDOW_2	You don't have any of the selected elixirs in inventory!
BONUS_CHANGER	Bonus change
BONUS_CHANGER_CHANGE	Change bonuses
BONUS_TITLE	Bonuses
BONUSES_FOR_FINISHING	Bonuses for completion
BOOSTER_WINDOW_CLOSE	Deactivate all
BOOSTER_WINDOW_TITLE	Mass use of elixirs
BUFF_INTELLIGENCE	Intelligence: {}
BUFF_SKILL_1	Blessing
BUFF_SKILL_2	Attack+
BUFF_SKILL_3	Dragon's Aid
CANNOT_DOING_PRIVATE_SHOP_OPEN	While your offline shop is open, you cannot do anything else.
CATEGORY_15	Sashes
CATEGORY_16	Enhance/Enchant
CATEGORY_17	Easter items
CATEGORY_18	Mounts
CATEGORY_19	Relics and melting
CATEGORY_20	Fish
CATEGORY_21	Trophy exchange for artifact chests
CATEGORY_22	Upgrade stones
CATEGORY_23	Summer items
CATEGORY_24	Summer costumes
CATEGORY_COSTUMES_COSTUME_WEAPON	Weapon Skins
CATEGORY_JEWELRY_ARMOR_WRIST	Bracelets
CHANGE_ATTR_SELECT	Bonus change
CHANGE_EQUIPMENT_CHANGE	Switch equipment
CHANGE_EQUIPMENT_TITLE	Equipment change
CHAT_OPEN_LINK	Do you want to open this link?
CHAT_OPEN_LINK_DANGER	Warning! This link may be dangerous!
CHEST_PREVIEW_CONTAINS_ITEM_TEXT	This chest contains:
CHEST_PREVIEW_TITLE	Drop preview
COLLECT_LOCATION_LABEL	Location:
COLLECTIONS_WARRIOR	Warrior
CREATE_CHARACTER	Create Character
CREATE_CUSTOMIZATION	Customization
CREATE_DETAILS	Details
CREATE_SELECT_COSTUME	Select Costume
CREATE_SELECT_GENDER	Select Gender
CUBE_CRAFT	Craft
CUBE_CRAFT_100	Craft 100x
CUBE_CRAFT_ALL	Craft All
CUBE_OK	OK
CUBE_RESULT_SUCCESS	Crafting completed successfully
CUBE_RESULT_TITLE	Crafting Result
CURRENT_MISSION	Available missions
DEMON_TOWER	Demon Tower
DETACH_METIN	Extract
DO_ALL_REFINE	Refine All
DO_CHANGE_ATTR	Change
DOUBLE_ACHIEVEMENT_POINTS	|cFF63f282DOUBLE ACHIEVEMENT POINTS DROP FROM METIN STONES AND BOSSES|h|r
DOUBLE_DROP_LOOT_TOOLTIP	100% chance for double drop
DOUBLE_ORE_EVENT	|cFF63f282DOUBLE ORE DROP|h|r
DRAGON_SOUL_REFINE_WITH_BUTTON	Upgrade using key: {}
DRAGONSOUL_CHANCE	Chance: |cFFf4be00{}%|r
DRAGONSOUL_GRADE_0	Raw
DRAGONSOUL_GRADE_1	Polished
DRAGONSOUL_GRADE_2	Rare
DRAGONSOUL_GRADE_3	Ancient
DRAGONSOUL_GRADE_4	Legendary
DRAGONSOUL_GRADE_5	Mythical
DRAGONSOUL_ONLY_MYTHIC_CAN_BE_SWITCHED	|cFFff9494Bonus change is only possible with mythical alchemy.|r
DRAGONSOUL_PLACE_DRAGON_SOUL_FIRST	|cFFff9494Place a Dragon Stone first.|r
DRAGONSOUL_PRICE	Price: |cFFc99f36200.000.000 {}
DRAGONSOUL_RENEW_TIME	Time renewal
DRAGONSOUL_WRONG_ATTR_CHANGE_ITEM	|cFFff9494This item cannot be used to change bonuses in alchemy.|r
DUNGEON_BOSS_DROP	Boss drop
DUNGEON_INFO	Dungeons
DUNGEON_INFO_COOLDOWN	Cooldown: %s
DUNGEON_INFO_DEVIL_BONUS	Strong against devils (+
DUNGEON_INFO_DROP_CHANCE	|cFFc9f1c0Drop chance:
DUNGEON_INFO_DROP_GLOVES_NORMAL	- |cFFf1e6c0Drop with gloves: 13 pcs.
DUNGEON_INFO_DROP_GLOVES_VIP	- |cFFf1e6c0Drop with gloves (VIP): 14 pcs.
DUNGEON_INFO_FASTEST_TIME	Fastest time: %s
DUNGEON_INFO_GLOVES_BONUSES	|cFFecffb7Possible bonuses (1 - 3):
DUNGEON_INFO_GO_TO_ENTRANCE_TOOL_TIP	Teleport to Entrance
DUNGEON_INFO_LEVEL_LIMIT	Level Limit: %d to %d
DUNGEON_INFO_MAIN_APPLY_TEXT	Monster types:
DUNGEON_INFO_MAIN_COMPLETION_COUNT	Number of completed runs:
DUNGEON_INFO_MAIN_COMPLETION_COUNT_BUTTON	Ranking: Number of completions
DUNGEON_INFO_MAIN_COOLDOWN	Remaining time:
DUNGEON_INFO_MAIN_DETAILS	Dungeon name
DUNGEON_INFO_MAIN_FASTEST_COMPLETION	Fastest completion:
DUNGEON_INFO_MAIN_FASTEST_COMPLETION_BUTTON	Ranking: Fastest completion
DUNGEON_INFO_MAIN_GREATEST_DAMAGE	Highest damage:
DUNGEON_INFO_MAIN_GREATEST_DAMAGE_BUTTON	Ranking: Highest damage
DUNGEON_INFO_MAIN_JOIN_BUTTON	Enter
DUNGEON_INFO_MAIN_LEVEL_LIMIT	Minimum level:
DUNGEON_INFO_MAIN_PASS_ITEM	Required pass:
DUNGEON_INFO_MAIN_REJOIN_BUTTON	Skip time
DUNGEON_INFO_MAIN_TITLE	Dungeon window
DUNGEON_INFO_MAIN_TYPE	Dungeon type:
DUNGEON_INFO_ORC_BONUS	Strong against orcs (+
DUNGEON_INFO_RANKING_HEADER_LEVEL	Level
DUNGEON_INFO_RANKING_HEADER_NAME	Name
DUNGEON_INFO_RANKING_HEADER_RANK	Rank
DUNGEON_INFO_RANKING_HEADER_SCORE	Score
DUNGEON_INFO_RANKING_TITLE	Dungeon Panel - Highscores
DUNGEON_INFO_TITLE	Expeditions
DUNGEON_INFO_TOTAL_FINISHED	Completions: %d
DUNGEON_INFO_TYPE	Type: %s
DUNGEON_RANKING	Ranking
DUNGEON_RANKING_TYPE_TOOL_TIP_01	Completion Ranking
DUNGEON_RANKING_TYPE_TOOL_TIP_02	Time Ranking
DUNGEON_RANKING_TYPE_TOOL_TIP_03	DMG Ranking
EASTER_MAP_2025	Easter Map
EXCHANGE_MONEY	Sum
FISH_GIVE_MISSION_BTN	Submit fish
FISH_LENGTH_DEFAULT	0.00 cm.
FISH_PROGRESS_INFO	11/|cFFFBA5EE20|h
FISHING_WINDOW_NAME	Fish Name
FISHWIKI_CATCHED_FISHES	Number caught: |cFF79fc790|h
FISHWIKI_CATCHED_FISHES_COUNT	Number caught: |cFF79fc79%d|h
FISHWIKI_GIVE_10_FISHES	Submit 10x |cFF79fc79Rainbow Trout|h|r with minimum length |cFF79fc79100 cm.|h
FISHWIKI_GIVE_CHANCE	Chance for successful submission: |cFF79fc7925%|h
FISHWIKI_GIVE_CHANCE_SUCCESS	Chance for successful submission: |cFF79fc79%d%%|h
FISHWIKI_GIVE_FISHES	Submit %d pcs. |cFF79fc79%s|h|r with minimum length |cFF79fc79%d cm.|h
FISHWIKI_LENGTH_RANKING	Ranking of biggest caught fish: |cFF79fc79|h
FISHWIKI_LENGTH_RANKING_BEST	Ranking of biggest caught fish: |cFF79fc79%s|h
FISHWIKI_LONGEST_FISH	Longest caught: |cFF79fc790 cm.|h
FISHWIKI_LONGEST_FISH_CM	Longest caught: |cFF79fc79%.2f cm.|h
FISHWIKI_MAIN_WINDOW	Fishing Collection
FISHWIKI_MOST_EXPENSIVE_FISH	Most expensive caught: |cFF79fc790 Yang|h
FISHWIKI_MOST_EXPENSIVE_FISH_YANG	Most expensive caught: |cFF79fc79%s Yang|h
FISHWIKI_PROGRESS_STATE	%d/|cFF79fc79%d|h
FISHWIKI_REWARD_FOR_MISSION	Reward: |cFF79fc79Strong against monsters +5%|h
FISHWIKI_REWARD_FOR_MISSION_FISH	Reward: |cFF79fc79%s|h
FISHWIKI_ROD_LEVEL	Fishing Rod +%d
FISHWIKI_ROD_LEVEL_0	Fishing Rod +0
FISHWIKI_SHOW_RANKING	Show ranking
FOV_OPTION	FOV
FOV_RESET_OPTION_TOOLTIP	Reset
GAME_OPTION_FONT	Font
GAME_OPTION_FONT_BIG	Bigger
GAME_OPTION_FONT_SMALL	Smaller
GAME_OPTION_MONSTERS	Monsters
GAME_OPTION_MONSTERS_DOGS	Wild dogs
GAME_OPTION_MONSTERS_NORMAL	Normal
GAME_OPTION_SKYBOX	Sky selection
GAME_OPTION_SKYBOX_DEFAULT	Default
GAME_OPTIONS_ACTIVATE_BUTTON	Activate
GAME_OPTIONS_ADD_TO_SPECIAL_INVENTORY	Move to special inventory.
GAME_OPTIONS_BUFFI_HIDE	Hide
GAME_OPTIONS_BUFFI_SHOW	Show
GAME_OPTIONS_DEACTIVATE_BUTTON	Deactivate
GAME_OPTIONS_DESCRIPTIONS_CATEGORY	Description
GAME_OPTIONS_FIND_CHESTS_DESC_1	Find chests hiding
GAME_OPTIONS_FIND_CHESTS_DESC_2	this item.
GAME_OPTIONS_HIDING_CATEGORY	Show/Hide
GAME_OPTIONS_MAIN_CATEGORY	General
GAME_OPTIONS_MOUNTS_HIDE	Hide
GAME_OPTIONS_MOUNTS_SHOW	Show
GAME_OPTIONS_MOUNTS_VISIBILITY	Mounts
GAME_OPTIONS_PETS_HIDE	Hide
GAME_OPTIONS_PETS_SHOW	Show
GAME_OPTIONS_PETS_VISIBILITY	Pets
GAME_OPTIONS_PULL_OUT	{} - Pull out
GAME_OPTIONS_SPLIT_OPTION	{} + {} - Split
GAME_OPTIONS_SYSTEM_CATEGORY	System
GIFT_SYSTEM_1	Promotional Code
GIFT_SYSTEM_2	Accept
GIFT_SYSTEM_3	Clear
GIFT_SYSTEM_6	Enter Code
GIFT_SYSTEM_7	Code:
GIVEAWAY_ITEM	Submit item
HELL_DUNGEON	Hell Gates
HELP_PAGE_1	Page 1
HELP_PAGE_2	Page 2
HORSE_HOE_TITLE	Horseshoe Crafting
HORSESHOE_PRICE	Price: 
HORSESHOE_REQUIRED_ITEMS	Required items
INCREASE_CHANCE_TOOLTIP	Increase the hand-in chance
INTROLOGIN_CONFIRM_MAIL	You must first activate account via email!
INVENTORY_EX_ALCHEMY	Alchemy
INVENTORY_EX_STACK_ITEMS	Move item
INVENTORY_RUNE_SYSTEM	Rune System
ITEM_PRICE_TITLE	[ Item Price ]
ITEMSHOP_ATTRIBUTE_BUY	Do you want to buy:
ITEMSHOP_ATTRIBUTE_EXP	|cFFFFCF48(EXP)|r
ITEMSHOP_ATTRIBUTE_PVP	|cFFFFCF48(PvP)|r
ITEMSHOP_EDITOR_ADD_ITEM	Add Item
ITEMSHOP_EDITOR_DELETE_ITEM	Delete Item
ITEMSHOP_EDITOR_EDIT_ITEM	Edit Item
ITEMSHOP_EDITOR_ITEM_ATTR	Bonus Information
ITEMSHOP_EDITOR_ITEM_ATTR_TEXT	Bonus %d
ITEMSHOP_EDITOR_ITEM_ATTR_VALUE_TEXT	Value %d
ITEMSHOP_EDITOR_ITEM_COUNT	Quantity
ITEMSHOP_EDITOR_ITEM_MAIN	Basic Item Information
ITEMSHOP_EDITOR_ITEM_NAME	Item Name
ITEMSHOP_EDITOR_ITEM_PRICE	Price
ITEMSHOP_EDITOR_ITEM_SOCKET	Soul Stones or Duration Information
ITEMSHOP_EDITOR_ITEM_SOCKET_TEXT	Stone %d
ITEMSHOP_NO_DISCOUNT_ITEMS	No items are currently discounted
ITEMSHOP_STORAGE_WINDOW_1	Select
ITEMSHOP_STORAGE_WINDOW_2	Item Shop
ITEMSHOP_STORAGE_WINDOW_3	Storage
ITEMSHOP_TITLE	Item Shop
ITEMSHOP_WINDOW_GET_DC	Click to top up DM
JUNGLE_DUNGEON	Ancient Jungle
KEYCHANGE_CANCLE	Cancel
KEYCHANGE_CH1	Channel 1
KEYCHANGE_CH2	Channel 2
KEYCHANGE_CH3	Channel 3
KEYCHANGE_CH4	Channel 4
KEYCHANGE_CH5	Channel 5
KEYCHANGE_CH6	Channel 6
KEYCHANGE_DODATKOWE	Additional Equipment
KEYCHANGE_DOPALACZE	Use Boosters
KEYCHANGE_DUNGEONY	Dungeon Panel
KEYCHANGE_ENTER	Bonuses/Alchemy/Sashes
KEYCHANGE_MARMURY	Marble Shop
KEYCHANGE_PET	Pet Panel
KEYCHANGE_PMISJE	Missions Panel
KEYCHANGE_POMOCNIK	Buffi Panel
KEYCHANGE_TELEPORTACJA	Teleportation
KEYCHANGE_TPBOSS	Tp Metins/Bosses
KEYCHANGE_ZAPIS	Save Position
LEFTOVER_TIME	|cFFBEB47DRemaining time:
LOCATION_TEXT	|cFFf1e6c0Location: |r-
LOGIN_BUTTON_TEXT	Login
LOGIN_CHANNEL_SELECT	Select Channel
LOGIN_ENTER_DATA	Enter your login details
LOGIN_ENV_DEV	Dev
LOGIN_ENV_LIVE	Live
LOGIN_LOAD_ACCOUNT	Load account - Hotkey - F%d
LOGIN_PANEL_TITLE	Login
LOGIN_SAVE_ACCOUNT	Save Account
LOGIN_SAVED_ACCOUNTS	Saved Accounts
LOGIN_SELECT_LANGUAGE	Select Language
LOW_LEVEL_TEXT	Required level: 0
MINIMAP_DUNGEON_INFO_REPEAT	Again
MINIMAP_DUNGEON_INFO_TIMER	Timer:
MINIMAP_FPS_INFO	FPS:{:3d}
MINING_CHEST_EVENT	|cFF63f282CHANCE FOR MINERS' CHEST DROP FROM ORES|h|r
MINING_EVENT_RENEWAL_HIT_DELAY	Can't do this so fast.
MISSION_CATEGORY_1	Biological research
MISSION_CATEGORY_2	Collector
MISSION_CATEGORY_3	Hunting
MISSION_CATEGORY_4	Bossology
MISSION_CATEGORY_5	Metinology
MISSION_CHOICE	Mission selection
MISSION_WINDOW_1	Mission window
MOUNT_BONUSES	Mount Bonuses
MOUNT_BONUS_NONE	No bonus
MOUNT_EQUIPMENT	Equipment
MOUNT_HORSESHOE	Horseshoe
MOUNT_IN_PREPARATION	Coming soon..
MOUNT_PASSIVE_ABILITIES	Passive Abilities
MOUNT_RIDE_TITLE	Mount
MOUNT_TOOLTIP_APPLY_ATTBONUS_BOSS	Strong against bosses
MOUNT_TOOLTIP_APPLY_ATTBONUS_MONSTER	Strong against monsters
MOUNT_TOOLTIP_APPLY_ATTBONUS_STONE	Strong against metin stones
MOUNT_TOOLTIP_BLOCK	Block chance
MOUNT_TOOLTIP_RESIST_MONSTER	Monster resistance
MOUNT_TOOLTIP_ATTBONUS_DUNGEON	Strong against bosses (dungeon)
MOUNT_TOOLTIP_MAX_HP	Max. HP
MOUNT_TOOLTIP_MOUNT_SPEED	Mount Speed
MOUNT_WINDOW_CURRENT_EXP	|cffBEB4A8|H|hExperience:|H|h |cff18f28d|H|h{} EXP|H|h
MOUNT_WINDOW_FEED_ITEM_1	|cffc99573|H|h(Lv. 1-24)|H|h
MOUNT_WINDOW_FEED_ITEM_2	|cffc99573|H|h(Lv. 25-49)|H|h
MOUNT_WINDOW_FEED_ITEM_3	|cffc99573|H|h(Lv. 50-74)|H|h
MOUNT_WINDOW_FEED_ITEM_4	|cffc99573|H|h(Lv. 75-100)|H|h
MOUNT_WINDOW_INFO_LEVEL	Each level gives you better bonuses
MOUNT_WINDOW_LEVEL	|cffb482ff|H|hLevel {}
MOUNT_WINDOW_TITLE	Mount window
NINJA_CLASSES	Archer | Assassin
NO_MOB_DATA	No data
OFFLINE_SHOP_BUY_ITEM	Do you want to buy %s %dx for %s?
OFFLINE_SHOP_BUY_ITEM2	Do you want to buy %s for %s?
OFFLINE_SHOP_EMOJI_TOOLTIP	|Eemoji/key_ctrl|e + |Eemoji/key_rclick|e - Remove item
OFFLINE_SHOP_EMOJI_TOOLTIP2	|Eemoji/key_rclick|e - Update item price(s)
OFFLINE_SHOP_EMOJI_TOOLTIP3	|Eemoji/key_ctrl|e + |Eemoji/key_rclick|e - Take item
OFFLINE_SHOP_LEFT_TIME	Remaining time: %s
OFFLINE_SHOP_NO_ITEMS_IN_SHOP	To create shop, you must put items in it!
OFFLINE_SHOP_REMAINING_TIME	Remaining time: 0 days
OFFLINE_SHOP_WARNING	If you don't see item you're looking for here because storage is full, you'll see more items when you collect items from storage.
OFFLINE_SHOP_WITHDRAW_YANG	Withdraw
OFFLINESHOP_AVERAGE_PRICE	Per piece: {}
OFFLINESHOP_AVERAGE_PRICE_INFO	<Average price information>
OFFLINESHOP_AVERAGE_PRICE_NO_INFO	No average price found!
OFFLINESHOP_AVERAGE_PRICE2	All: {}
OFFLINESHOP_CHANGE_ALL_PRICE	Update all prices of same item
OFFLINESHOP_EDIT_SHOPNAME_DESCRIPTION	Enter new shop name
OFFLINESHOP_EDIT_SHOPNAME_DESCRIPTION2	New name:
OFFLINESHOP_FILTER_TITLE	Filters
OFFLINESHOP_INPUT_INFO	Enter price you want to
OFFLINESHOP_INPUT_INFO2	sell this item for
OFFLINESHOP_NO_MONEY_TO_WITHDRAW	No yang to withdraw.
OFFLINESHOP_NO_NAME	Your shop has no name!
OFFLINESHOP_NOTIF_CLOSE_ALL	Close all
OFFLINESHOP_NOTIF_ITEM_INFO	%s x%d sold for %d.
OFFLINESHOP_RESULT_PER_PAGE	Results per page
OFFLINESHOP_RESULT_PER_PAGE_ITEM	25 items per page
OFFLINESHOP_RESULT_PER_PAGE_ITEM2	50 items per page
OFFLINESHOP_RESULT_PER_PAGE_ITEM3	100 items per page
OFFLINESHOP_SELL_WITH_AVG_PRICE	Sell for average price
OFFLINESHOP_SELL_WITH_AVG_PRICE2	Sell 10% above avg. price
OFFLINESHOP_SELL_WITH_AVG_PRICE3	Sell 10% below avg. price
OFFLINESHOP_SHOP_COLOR	Set shop name color
OFFLINESHOP_SHOP_DECO_0	Normal
OFFLINESHOP_SHOP_DECO_1	1001 Nights
OFFLINESHOP_SHOP_DECO_2	BBQ King
OFFLINESHOP_SHOP_DECO_3	Treasure Hunters
OFFLINESHOP_SHOP_DECO_4	Fire Merchant
OFFLINESHOP_SHOP_DECO_5	Armorer
OFFLINESHOP_SHOP_DECO_TITLE	Shop decoration
OFFLINESHOP_TITLE_NAME	Name
OFFLINESHOP_TITLE_OTHER	Other
OFFLINESHOP_TITLE_PRICE	Price
OFFLINESHOP_TOOLTIP_RIGHT_CLICK_FOR_SALE	|Eemoji/key_rclick|e - Add item to shop
OFFLINESHOP_TOOLTIP_RIGHT_CLICK_FOR_SALE2	|Eemoji/key_ctrl|e + |Eemoji/key_rclick|e - Quick add item to shop
OFFLINESHOP_TOTAL_PRICE_OF_SHOP	Total price of all items in shop
OFFLINESHOP_TOTAL_YANG_AMOUNT	Total: {}
OFFSHOP_DECORATION_SET	Set shop decoration
OPTION_AUTOBUFF	Autobuff
OPTION_TILING	Graphics
OPTION_TILING_APPLY	Apply
OPTION_TILING_CPU	CPU
OPTION_TILING_GPU	GPU
PET_ATTR_CONFIRMATION	Change shop name
CHANGE_LANGUAGE_QUESTION	Do you want to change the language?
COMPANION_TITLE	Companions
COMPANION_LABEL_NAME	Name
COMPANION_LABEL_FEED_ITEM	Feed item
COMPANION_LABEL_LEVEL	Level
COMPANION_PET_EXP_WITH_CHAR	EXP with character
COMPANION_PET_FEED_1	 Feed Lv.1
COMPANION_PET_FEED_2	 Feed Lv.2
COMPANION_PET_FEED_3	 Feed Lv.3
PET_EQUIPMENT	Equipment
PET_GENERAL_INFORMATIONS	General Information
PET_INFO_1	In case you have all skills at P,
PET_INFO_2	you'll receive additional bonus |cFFc8ff9c+30%|r to all skills.
PET_INFO_3	Selected skill: {}
PET_INFO_4	Extra bonus: |cFFc8ff9c+{}|r
PET_SKILS	Passive skills
PET_TEXT	Pet
PIECES_OF_ITEM	Pcs.
POLY_MARBLES_TITLE	Transformation shop
POLYSYSTEM_CHOOSE_SKIN	Change skin
POLYSYSTEM_CHOOSE_SKIN_SELECT	Change
POLYSYSTEM_NO_BONUSES	No bonuses
PREMIUM_PRIVATE_SHOP_DECO_APPEARANCE	Appearance
PREMIUM_PRIVATE_SHOP_DECO_TITLE	Title
PREMIUM_PRIVATE_SHOP_MARKET_PRICE_TITLE	Market Price
PREMIUM_PRIVATE_SHOP_PRICE_TITLE	Sale Price
PREMIUM_PRIVATE_SHOP_SALE_DATE	Date
PRIVATE_SHOP_CLOSE_QUESTION	Do you want to close the private shop?
PRIVATESHOPSEARCH_APPLY_FILTER	Apply Filter
PRIVATESHOPSEARCH_ARMOR	Equipment
PRIVATESHOPSEARCH_ATTR_FILTER_CONFIG	Attribute Filter
PRIVATESHOPSEARCH_BELL	Bells
PRIVATESHOPSEARCH_BELT	Belts
PRIVATESHOPSEARCH_BLEND	Potions
PRIVATESHOPSEARCH_BODY	Armor
PRIVATESHOPSEARCH_BOW	Bows
PRIVATESHOPSEARCH_BUYTIME	Do you want to buy the selected item?
PRIVATESHOPSEARCH_CLEAR_FILTER_CONFIG	Clear Filter
PRIVATESHOPSEARCH_CLEAR_SELECTED_ITEMS	Clear Selected Items (%d / %d)
PRIVATESHOPSEARCH_CONTACT_SELLER	Contact Seller
PRIVATESHOPSEARCH_COSTUME	Costumes
PRIVATESHOPSEARCH_COSTUME_ACCE	Sashes
PRIVATESHOPSEARCH_COSTUME_ACCE_SKIN	Sash costumes
PRIVATESHOPSEARCH_COSTUME_MOUNT	Mounts
PRIVATESHOPSEARCH_COSTUMEBODY	Costume
PRIVATESHOPSEARCH_COSTUMEHAIR	Hair
PRIVATESHOPSEARCH_DAGGER	Daggers
PRIVATESHOPSEARCH_EAR	Earrings
PRIVATESHOPSEARCH_FAN	Fans
PRIVATESHOPSEARCH_FILTER_SAVE_TITLE	Filter Name
PRIVATESHOPSEARCH_FILTER_SELECT_TITLE	Filter Selection
PRIVATESHOPSEARCH_FILTER_TITLE	Filters
PRIVATESHOPSEARCH_FISH	Fish
PRIVATESHOPSEARCH_FOOTS	Shoes
PRIVATESHOPSEARCH_GENERAL_FILTER_CONFIG	General Filter
PRIVATESHOPSEARCH_GIFTBOX	Chests
PRIVATESHOPSEARCH_GLOVE	Gloves
PRIVATESHOPSEARCH_HEAD	Helmets
PRIVATESHOPSEARCH_HIDE_FILTER_SELECT_DIALOG	Hide Filter Window
PRIVATESHOPSEARCH_ITEM_SEARCH_MODE	Mode: Search by Item
PRIVATESHOPSEARCH_METIN	Metin Stones
PRIVATESHOPSEARCH_NECK	Necklaces
PRIVATESHOPSEARCH_NEED_ITEM_BUY	You cannot purchase any items without the correct bundle.
PRIVATESHOPSEARCH_NEED_ITEM_FIND	You cannot search for any items without the correct bundle.
PRIVATESHOPSEARCH_PAGE_FIRST_PREV	First Page
PRIVATESHOPSEARCH_PAGE_LAST_NEXT	Last Page
PRIVATESHOPSEARCH_PAGE_NEXT	Next Page
PRIVATESHOPSEARCH_PAGE_PREV	Previous Page
PRIVATESHOPSEARCH_PLAYER_SEARCH_MODE	Mode: Search by Player
PRIVATESHOPSEARCH_REMOVE_FILTER	Remove Filter
PRIVATESHOPSEARCH_RESOURCE	Upgrade items
PRIVATESHOPSEARCH_SAVE_FILTER	Save Filter
PRIVATESHOPSEARCH_SEARCH_SELLER	View Seller's Offers
PRIVATESHOPSEARCH_SHIELD	Shields
PRIVATESHOPSEARCH_SKILLBOOK	Skill books
PRIVATESHOPSEARCH_SWORD	One-handed swords
PRIVATESHOPSEARCH_TWOSWORD	Two-handed swords
PRIVATESHOPSEARCH_USEITEM	Consumable items
PRIVATESHOPSEARCH_VIEW_CATEGORY	Show Category Selection
PRIVATESHOPSEARCH_VIEW_FILTER	Show Filter Configuration
PRIVATESHOPSEARCH_VIEW_FILTER_SELECT_DIALOG	Show Filter Window
PRIVATESHOPSEARCH_WEAPON	Weapons
PROMO_CODE_INFO	You can find promo codes on our Facebook page or Discord.
PROMO_CODE_INPUT	Enter promo code
PROMO_CODE_USE	Activate
QUEUE_TITLE	Queue
RANKING_LEVEL_PREFIX	Lv. {}
RANKING_WINDOW_CATEGORY_ALCHEMY	Dragon stones upgraded
RANKING_WINDOW_CATEGORY_BOSSES	Bosses killed
RANKING_WINDOW_CATEGORY_DRAGON_COINS	Dragon coins spent
RANKING_WINDOW_CATEGORY_DUNGEONS	Dungeons
RANKING_WINDOW_CATEGORY_MONSTERS	Monsters killed
RANKING_WINDOW_CATEGORY_REFINE	Items upgraded
RANKING_WINDOW_CATEGORY_STONES	Metin stones destroyed
RANKING_WINDOW_LEVEL_RANK_LIMIT	Level ranking shows characters with level 75+.
RANKING_WINDOW_NO_CHARACTERS	No characters
RANKING_WINDOW_NO_POSITION	No position
RANKING_WINDOW_POSITION	Position %s
RANKING_WINDOW_RANKING_TITLE	Ranking
RANKING_WINDOW_SERVER_RANKING_DO_NOT_RESET	Server ranking doesn't reset.
RANKING_WINDOW_WEEKLY_RANK_RESET_TIME	Ranking reset in:|cFFF19BFF
RANKING_WINDOW_WEEKLY_RANK_RESET_TIME_UPDATE	Ranking reset in: |cFFcf9bff%s
REDUCE_TIME_TOOLTIP	Reduce the waiting time
REMOVE_ITEM_CLEAR	Clear Window
REMOVE_ITEM_DIALOG	{} + {} - Quick add
REMOVE_ITEM_REMOVE	Remove Items
REMOVE_ITEM_TITLE	Remove Items
RESP_DIALOG_OPEN_AUTOMATICALLY	Open automatically (when changing map / channel)
RESP_ERROR_TEXT	No Data
RESP_MINIMAP_BOSS	Remaining Bosses
RESP_MINIMAP_METIN	Remaining Metins
RESP_MOB_HEADER	Bosses / Metins
RESP_TITLE	Teleport to Bosses / Metins
RESPAWN_LEVEL_RANGE	Lv. 140 - 150
RESPAWN_UNDEAD	Undead
RUNE_SET_BONUS_1	Attack value +20%
RUNE_SET_BONUS_2	Average damage +15%
RUNE_SET_BONUS_3	Strong against humans +25%
RUNE_SET_BONUS_4	Attack value +30%
RUNE_SET_BONUS_5	Average damage +25%
RUNE_SET_BONUS_6	Strong against humans +40%
RUNEWINDOW_TITLE	Runes
SASH_COMBINATION_SHORTCUT	Combine using key:
SAVE_LOCATION_DELETE_CONFIRM	Are you sure you want to delete this save?
SAVE_LOCATION_TITLE	Saved Locations
SAVE_MAPS_TITLE	Position saving
SAVEMAP_LOAD	Load
SAVEMAP_SAVE	Save
SAVEMAP_TEST	Test
SCORPION_DUNGEON	Scorpion Ruins
SEARCH_IN_SHOPS_SHORTCUT	Search in shops
SECONDARY_LEVEL_0	None
SECONDARY_LEVEL_1	Bronze I
SECONDARY_LEVEL_10	Silver V
SECONDARY_LEVEL_11	Gold I
SECONDARY_LEVEL_12	Gold II
SECONDARY_LEVEL_13	Gold III
SECONDARY_LEVEL_14	Gold IV
SECONDARY_LEVEL_15	Gold V
SECONDARY_LEVEL_16	Platinum I
SECONDARY_LEVEL_17	Platinum II
SECONDARY_LEVEL_18	Platinum III
SECONDARY_LEVEL_19	Platinum IV
SECONDARY_LEVEL_2	Bronze II
SECONDARY_LEVEL_20	Platinum V
SECONDARY_LEVEL_21	Diamond I
SECONDARY_LEVEL_22	Diamond II
SECONDARY_LEVEL_23	Diamond III
SECONDARY_LEVEL_24	Diamond IV
SECONDARY_LEVEL_25	Diamond V
SECONDARY_LEVEL_26	Ruby I
SECONDARY_LEVEL_27	Ruby II
SECONDARY_LEVEL_28	Ruby III
SECONDARY_LEVEL_29	Ruby IV
SECONDARY_LEVEL_3	Bronze III
SECONDARY_LEVEL_30	Ruby V
SECONDARY_LEVEL_4	Bronze IV
SECONDARY_LEVEL_5	Bronze V
SECONDARY_LEVEL_6	Silver I
SECONDARY_LEVEL_7	Silver II
SECONDARY_LEVEL_8	Silver III
SECONDARY_LEVEL_9	Silver IV
SECONDARY_LEVEL_BONUS_NONE	No bonus
SECURITY_ANSWER_IS_WRONG	Answer is incorrect, try again! Note: Wrong choice reduces time by 5 seconds.
SECURITY_ANSWER_SUCCESS	Anti-bot verification successfully completed, you can continue playing.
SECURITY_CLEAR	Clear
SECURITY_CONFIRM	Confirm
SECURITY_FIND_THE_DIFFERENT	Click on image that differs from others!
SECURITY_REMAINING_TIME	Remaining time: {:.1f}
SECURITY_SELECT_ANSWER	Enter numbers above!
SECURITY_SORT_IMAGES	Sort numbers by dragging towards {}!
SECURITY_SORT_IMAGES2	small to big
SECURITY_SORT_IMAGES3	big to small
SECURITY_YOU_HAVE_ONE_MORE_CHANGE	Wrong choice, try again! Next wrong choice will disconnect you.
SELECT_BACK_BUTTON	Back
SELECT_CHAR_DETAILS	Character Details
SELECT_CHAR_SELECTION	Character Selection
SELECT_DELETE_BUTTON	Delete
SELECT_EXIT_BUTTON	Exit
SELECT_EXP	Experience
SELECT_GUILD_LABEL	Guild
SELECT_KINGDOM	Kingdom
SELECT_PLAY_BUTTON	Play
SELECT_RANK	Rank
SELECT_STATISTICS	Statistics
SELECT_STATS_DEX	DEX
SELECT_STATS_HP	HP
SELECT_STATS_SP	SP
SELECT_STATS_STR	STR
SETTINGS	Settings
SHAMAN_CLASSES	Dragon | Healer
SHIP_DUNGEON_1	Ghost Ship (I)
SHIP_DUNGEON_2	Ghost Ship (II)
SHOP_BUY_NOTIF_0	was sold.
SHOP_BUY_NOTIF_1	yang was added to your storage.
SHOP_MONEY_NOT_ENOUGH	Not enough yang!
SHOP_MONEY_NOT_ENOUGH2	Total price of products you want to add to cart cannot be higher than your balance.
SHOP_PRICE_WON_DEFAULT	0 Won
SHOP_PRICE_YANG_DEFAULT	0 Yang
SHOP_SEARCH_ACCE_GRADE_FILTER_0	Common
SHOP_SEARCH_ACCE_GRADE_FILTER_1	Fine
SHOP_SEARCH_ACCE_GRADE_FILTER_2	Noble
SHOP_SEARCH_ACCE_GRADE_FILTER_3	Royal
SHOP_SEARCH_ACCE_GRADE_FILTER_TITLE	Sash level
SHOP_SEARCH_ADD_ITEMS_TO_THE_CART_FIRST	To perform this action you must first select items.
SHOP_SEARCH_ADD_TO_BASKET	Add item to basket
SHOP_SEARCH_ALL	All categories
SHOP_SEARCH_BUY_CONFIRM	Do you really want to buy %s?
SHOP_SEARCH_BUY_SELECTED_ITEMS	Buy selected items
SHOP_SEARCH_BUY_SELECTED_ITEMS_CONFIRM	Do you really want to buy these %d items?
SHOP_SEARCH_CLEAR	Clear
SHOP_SEARCH_CLEAR_CART_FIRST	You can perform this action only when no items are selected.
SHOP_SEARCH_CLEAR_SHOPS	Clear shop selection
SHOP_SEARCH_DS_CLARITY_FILTER_0	Dull
SHOP_SEARCH_DS_CLARITY_FILTER_1	Clear
SHOP_SEARCH_DS_CLARITY_FILTER_2	Flawless
SHOP_SEARCH_DS_CLARITY_FILTER_3	Brilliant
SHOP_SEARCH_DS_CLARITY_FILTER_4	Excellent
SHOP_SEARCH_DS_CLARITY_FILTER_TITLE	Dragon Alchemy Clarity
SHOP_SEARCH_DS_GRADE_FILTER_TITLE	Dragon Alchemy Level
SHOP_SEARCH_ENTER_ITEMNAME	Search by item name
SHOP_SEARCH_FILTER_0_0	Min. Count
SHOP_SEARCH_FILTER_0_1	Max. Count
SHOP_SEARCH_FILTER_1_0	Min. Level
SHOP_SEARCH_FILTER_1_1	Max. Level
SHOP_SEARCH_FILTER_2_0	Min. Absorb.
SHOP_SEARCH_FILTER_2_1	Max. Absorb.
SHOP_SEARCH_FILTER_3_0	Min. Average
SHOP_SEARCH_FILTER_4_0	Min. Price
SHOP_SEARCH_FILTER_4_1	Max. Price
SHOP_SEARCH_ITEM_PRICE_PER_COUNT	Price per piece: %s
SHOP_SEARCH_MULTIBUY_ACTIVATED	You activated bulk purchase, now select items.
SHOP_SEARCH_NOT_RESULT_FOUND	No results found!
SHOP_SEARCH_REMOVE_FROM_THE_BASKET	Remove item from basket
SHOP_SEARCH_SEARCH_BY_PLAYERNAME	Search by player name
SHOP_SEARCH_SEARCH_BY_PLAYERNAME2	Search by player name
SHOP_SEARCH_SEARCH_ITEM	Search item
SHOP_SEARCH_SEARCH_ITEMS	Search items
SHOP_SEARCH_TITLE	Shop search
SHOPSEARCH_FIND_BY_NAME	Find item by name
SHOPSEARCH_SEARCH_IN_CATEGORY	Search items in category
SHOPSEARCH_SEARCH_ITEMS	Search items
SHOPSEARCH_TITLE	Search
SKILL_ACTIVE	Active
SKILL_BOOK_INVENTORY	Skill Books
SKILL_GROUP1	Group 1
SKILL_GROUP2	Group 2
SKILL_SELECT_TITLE	Select Skills
SPECIAL_INVENTORY	Special inventory
SPECIAL_INVENTORY_SETTINGS	Inventory settings
SPIDER_DUNGEON	Spider Queen's Web
STAT_TOOLTIP	{} + {} - Quick split
STATS_ADD	Add
STONE_DETACH_TITLE	Soul stone removal
STONEWINDOW_TITLE	Fragment crafting
SUMMER_DUNGEON	Solargon's Cave
SURA_CLASSES	Weaponry | Black Magic
SWITCH_AVERAGE_EVENT	|cFF63f282Chance to roll average 63%|r
SWITCH_AVERAGE_EVENT_TEXT	|cFF63f282Chance for bigger average damage|r
SWITCH_RARE_EVENT	|cFF63f282Easier rolling 6/7 bonuses|r
SWITCH_RUNE_EVENT	|cFF63f282Easier rolling relics|r
SWITCH_RUNE_EVENT_TEXT	|cFF63f282Bigger chance for 3rd grade relics|r
SWITCHBOT_ALTERNATIVE	Alternative
SWITCHBOT_INSTANT	Instant switching
SWITCHBOT_INSTANT_COUNT_TITLE	Number of rolls:
SWITCHBOT_SELECT_ITEM_FIRST	You must select the item whose bonuses you want to switch.
TARGET_RACE_FLAG_ANIMAL	Animal
TARGET_RACE_FLAG_BOSS	Boss
TARGET_RACE_FLAG_DARK	Darkness
TARGET_RACE_FLAG_DESERT	Desert
TARGET_RACE_FLAG_DEVIL	Devil
TARGET_RACE_FLAG_DUNGEON	Dungeon
TARGET_RACE_FLAG_EARTH	Earth
TARGET_RACE_FLAG_ELEC	Lightning
TARGET_RACE_FLAG_FIRE	Fire
TARGET_RACE_FLAG_HUMAN	Human
TARGET_RACE_FLAG_ICE	Ice
TARGET_RACE_FLAG_INSECT	Insect
TARGET_RACE_FLAG_LEGENDA	Legend
TARGET_RACE_FLAG_MILGYO	Esoteric
TARGET_RACE_FLAG_ORC	Orc
TARGET_RACE_FLAG_STONE	Metin stone
TARGET_RACE_FLAG_TREE	Forest
TARGET_RACE_FLAG_UNDEAD	Undead
TARGET_RACE_FLAG_WIND	Wind
TARGET_RACE_FLAG_WLADCA	Ruler
TITLE_0_0	Hunter III
TITLE_0_1	Hunter II
TITLE_0_2	Hunter I
TITLE_1_0	Executioner III
TITLE_1_1	Executioner II
TITLE_1_2	Executioner I
TITLE_2_0	Destroyer III
TITLE_2_1	Destroyer II
TITLE_2_2	Destroyer I
TITLE_3_0	Alchemist III
TITLE_3_1	Alchemist II
TITLE_3_2	Alchemist I
TITLE_4_0	Adventurer III
TITLE_4_1	Adventurer II
TITLE_4_2	Adventurer I
TITLE_5_0	Lucky III
TITLE_5_1	Lucky II
TITLE_5_2	Lucky I
TITLE_6_0	Rich III
TITLE_6_1	Rich II
TITLE_6_2	Rich I
TITLE_BONUS	Bonus
TITLE_BONUS_0_0	Strong against monsters +15%
TITLE_BONUS_0_1	Strong against monsters +10%
TITLE_BONUS_0_2	Strong against monsters +5%
TITLE_BONUS_1_0	Strong against bosses +15%
TITLE_BONUS_1_1	Strong against bosses +10%
TITLE_BONUS_1_2	Strong against bosses +5%
TITLE_BONUS_2_0	Strong against metin stones +15%
TITLE_BONUS_2_1	Strong against metin stones +10%
TITLE_BONUS_2_2	Strong against metin stones +5%
TITLE_BONUS_3_0	Strength in dungeons +15%
TITLE_BONUS_3_1	Strength in dungeons +10%
TITLE_BONUS_3_2	Strength in dungeons +5%
TITLE_BONUS_4_0	Upgrade chance +20%
TITLE_BONUS_4_1	Upgrade chance +12%
TITLE_BONUS_4_2	Upgrade chance +8%
TITLE_BONUS_5_0	Enhancement chance +10%
TITLE_BONUS_5_1	Enhancement chance +5%
TITLE_BONUS_5_2	Enhancement chance +3%
TITLE_BONUS_6_0	Prestige :)
TITLE_BONUS_6_1	Prestige :)
TITLE_BONUS_6_2	Prestige :)
TOOLTIP_APPLY_ATTBONUS_ENCHANT_DARK_POLY	Strong against darkness +%d%%
TOOLTIP_APPLY_ATTBONUS_HUMAN_POLY	Strong against humans +%d%%
TOOLTIP_APPLY_ATTBONUS_MAX_HP_POLY	Max. HP: +%d
TOOLTIP_APPLY_ATTBONUS_WLADCA_POLY	Strong against rulers +%d%%
TOOLTIP_ATTBONUS_ELEMENT	Strong against elements +%d%%	SA
TOOLTIP_ATTBONUS_ELEMENT_POLY	Strong against elements +%d%%
TOOLTIP_ATTBONUS_PVM_SKILL	PVM Skill damage +%d%%	SA
TOOLTIP_BONUS_CAN_BE_USE_X_TIMES	This bonus will be used: %dx
TOOLTIP_DEFBONUS_ELEMENT	Resistance against elements +%d%%	SA
TOOLTIP_DOUBLE_LOOT_DROP	Chance for double drop +%d%%	SA
TOOLTIP_DOUBLE_LOOT_SUMMER	Chance for double drop in shimmering lagoon +%d%%	SA
TOOLTIP_FISH_PRICE	Price: %s
TOOLTIP_FISHING_BIGGER_FISH_CHANCE	Chance for bigger fish +%d%%	SA
TOOLTIP_FISHING_INSTANT_CATCH_CHANCE	+%d%% chance for instant catch	SA
TOOLTIP_FISHING_MORE_POINTS_CHANCE	Chance for more points +%d%%	SA
TOOLTIP_FISHING_MORE_YANG_MULTIPLIER	More yang from fish +%d%%	SA
TOOLTIP_FISHING_NEXT_SECTION_CHANCE	Chance for rarer fish +%d%%	SA
TOOLTIP_FISHING_SKILL_BONUS_BIGGER_FISH	Chance for bigger fish +%d%%
TOOLTIP_FISHING_SKILL_BONUS_INSTANT	Chance for instant catch +%d%%
TOOLTIP_FISHING_SKILL_BONUS_NEXT	Next bonuses per level:
TOOLTIP_FISHING_SKILL_BONUS_NOW	Current bonuses per level:
TOOLTIP_FISHING_SKILL_BONUS_POINTS	Chance for more points +%d%%
TOOLTIP_FISHING_SKILL_BONUS_RARE	Chance for rarer fish +%d%%
TOOLTIP_FISHING_SKILL_BONUS_YANG	More yang from fish +%d%%
TOOLTIP_FISHING_SKILL_MAX	Skill is at maximum level!
TOOLTIP_FISHING_SUCCESS_CHANCE	Chance to catch fish +%d%%	SA
TOOLTIP_FISHINGROD_CAN_USE	Bonus will be used: %dx more
TOOLTIP_ITEM_MOUNT_LIMIT_LEVEL	|cffBEB4A8|H|hFrom mount level:|H|h |cff18f28d|H|h%d|H|h
TOOLTIP_MALL_PREMIUM_MINE	Chance to mine ore +5%, chance for more ore +5%, chance for more points +20%, Mining time reduced by 1 second.	SNA
TOOLTIP_MINING_LESS_MINE_TIME	Mining time reduced by %dsec.	SA
TOOLTIP_MINING_MORE_ORES_CHANCE	Chance for more ore pieces +%d%%	SA
TOOLTIP_MINING_MORE_POINTS	Chance for more points +%d%%	SA
TOOLTIP_MINING_SUCCESS_CHANCE	Chance to mine ore +%d%%	SA
TOOLTIP_TOGGLE_ACTIVE	Active
UPGRADE_CHANCE_EXTRA	Upgrade chance: |c{color}{percentage}% (+{percentageExtra}%)
UPGRADE_ITEMS_INVENTORY	Upgraders
VALENTINE_EVENT	|cFFf263f0Valentine chocolates drop|r
WARRIOR_CLASSES	Mental | Body
WEEKLY_RANK_CAT_1	Monsters killed
WEEKLY_RANK_CAT_2	Bosses killed
WEEKLY_RANK_CAT_3	Metin stones destroyed
WEEKLY_RANK_CAT_4	Dungeons completed
WEEKLY_RANK_CAT_5	Alchemy upgraded
WEEKLY_RANK_CAT_6	Items upgraded
WEEKLY_RANK_CAT_7	DM spent
WEEKLY_RANK_CATEGORY_NAME	Category
WEEKLY_RANK_DEACTIVATE_TITLE	Deactivate title
WEEKLY_RANK_GLOBAL_RANKING	Global ranking
WEEKLY_RANK_REFRESH_TIME	Ranking refreshes every 10 minutes.
WEEKLY_RANK_TITLES	Titles
WEEKLY_RANK_YOUR_STATS	Your statistics
WEEKLY_RANK_YOUR_TITLES_INFO	Information about your titles
WHEEL_GAME_CHEQUE_MODE	For Won
WHEEL_GAME_ITEM_GOLD_COST	1x - 300 Won.
WHEEL_GAME_ITEM_MODE	For Summer Tokens
WHEEL_GAME_ITEM_WHEEL_COST	Cost: 1x Token
WHEEL_GAME_SKIP_ANIMATION	Skip animation
WHEEL_GAME_TITLE	Summer Wheel of Fortune
WHEEL_OF_FORTUNE_REWARDS	Rewards:
WHEEL_REWARD_TEXT	You received
WHEEL_REWARD_TEXT_1	reward can be found in inventory
WHEEL_REWARD_TITLE	Summer Wheel of Fortune
WHISPER_SEARCH_PLAYER_SHOP	Search player's shop
WONEXCHANGE_TITLE_BUY	Buy Won
WONEXCHANGE_TITLE_SELL	Sell Won
WORLDBOSS_GUARD_NAME	Announcement
WUKONG_DUNGEON	Wukong Mountains
SECONDARY_LEVEL_TITLE	Achievement points levels
SECONDARY_LEVEL_NONE	None
SECONDARY_LEVEL_CURRENT	Current Level
SECONDARY_LEVEL_NEXT	Next Level
SECONDARY_LEVEL_CURRENT_BONUSES	Current Level Bonuses
SECONDARY_LEVEL_NEXT_BONUSES	Next Level Bonuses
SECONDARY_LEVEL_REQUIRED_ITEMS	Required Items
SECONDARY_LEVEL_INCREASE_LEVEL	Increasing Level
SECONDARY_LEVEL_CHANCE	Chance:
SECONDARY_LEVEL_REQUIRED_AP	Price:
SECONDARY_LEVEL_LUCK	Gamble
SECONDARY_LEVEL_GUARANTEED	Guaranteed
SECONDARY_LEVEL_INCREASE_BUTTON	Level Up
ITEMSHOP_BTN_BUY	BUY
ITEMSHOP_BTN_CONFIRM	Confirm
ITEMSHOP_VOUCHER_TITLE	ENTER PROMO CODE
ITEMSHOP_VOUCHER_INFO_1	You can find promo codes
ITEMSHOP_VOUCHER_INFO_2	on our Discord and Fanpage.
ITEMSHOP_BTN_SPIN	SPIN
BATTLEPASS_BUY_PREMIUM	Buy Premium
BATTLEPASS_BTN_PREVIOUS	Previous
BATTLEPASS_BTN_NEXT	Next
BATTLEPASS_BTN_BACK	Back
BATTLEPASS_BTN_QUESTS	View Quests
MAINTENANCE_TITLE	[ Maintenance System ]
MAINTENANCE_ADMIN_TITLE	Maintenance Panel
MAINTENANCE_ADMIN_DELAY	|cfff8d090Time until server restart:
MAINTENANCE_ADMIN_DURATION	|cfff8d090Maintenance duration:
MAINTENANCE_ADMIN_LABEL_HOUR	Hours
MAINTENANCE_ADMIN_LABEL_MIN	Minutes
MAINTENANCE_ADMIN_LABEL_SEC	Seconds
MAINTENANCE_ADMIN_START	Start
MAINTENANCE_ADMIN_CANCEL	Cancel
SAVE_LOCATION_TELEPORT	Teleport:
SAVE_LOCATION_INPUT_NAME	Enter name
GAME_OPTIONS_VOICE_CHAT_CATEGORY	Voice chat
VOICE_CHAT_INSTRUCTION1	Hold the talk key to talk.
VOICE_CHAT_INSTRUCTION2	Works from level 50.
VOICE_CHAT_INSTRUCTION3	Choose a channel: local, party or guild.
VOICE_CHAT_INSTRUCTION4	Click a device to change it.
VOICE_CHAT_MIC_DEVICE	Microphone (device):
VOICE_CHAT_SPK_DEVICE	Speaker (device):
VOICE_CHAT_MIC_VOLUME	Microphone volume:
VOICE_CHAT_HEAR_VOLUME	Listening volume:
VOICE_CHAT_ENABLE	Voice chat:
VOICE_CHAT_ON	On
VOICE_CHAT_OFF	Off
VOICE_CHAT_PTT_KEY_LABEL	Talk key:
VOICE_CHAT_CHANNEL	Voice channel:
VOICE_CHAT_LOCAL	Local
VOICE_CHAT_PARTY	Party
VOICE_CHAT_GUILD	Guild
