1	WARRIOR	Three-Way Cut	Triple Cut	Triple Slash	Cut the enemy at lightning speed.	Physical melee attack (3x)	Frontal area of effect	Strengthened by STR		ATTACK_SKILL|NEED_TARGET|WEAPON_LIMITATION|IGNORE_BLOCK	SWORD|TWO_HANDED	samyeon	1	4			Total attack value: %.0f-%.0f	(1.1*MinATK + (0.1*MinATK + 1.5*STR)*SkillPoint) * 3	(1.1*MaxATK + (0.1*MaxATK + 1.5*STR)*SkillPoint) * 3			
2	WARRIOR	Sword Spin	Sword Dance	Cyclone	Spin the sword to attack several enemies.	Physical melee attack	Area of effect	Knockback	Strengthened by STR, DEX, VIT	ATTACK_SKILL|CAN_CHANGE_DIRECTION|WEAPON_LIMITATION|IGNORE_BLOCK	SWORD|TWO_HANDED	palbang	2	4			Attack value: %.0f-%.0f	3*MinATK + (0.8*MinATK + STR*6 + DEX*2 + CON) * SkillPoint	3*MaxATK + (0.8*MaxATK + STR*6 + DEX*2 + CON) * SkillPoint			
3	WARRIOR	Berserk	Fury	Frenzy	Only concentrate on attacking.	Buff	Increases attack speed	Increases movement speed	Increases received damage	STANDING_SKILL		jeongwi	3	4			Attack speed: +%.0f%%	50 * SkillPoint		Movement speed: +%.0f%%	20 * SkillPoint	
4	WARRIOR	Aura of the Sword	Spiritual Sword	Phantom Sword	Increases attack value for a period of time.	Buff	Increases attack value	Strengthened by STR		STANDING_SKILL|WEAPON_LIMITATION|IGNORE_BLOCK	SWORD|TWO_HANDED	geomgyeong	4	4			Attack value: +%.0f	(100 + STR) * SkillPoint				
5	WARRIOR	Dash	Bullet Dash	Powerful Attack	You attack as fast as a bullet!	Physical melee attack	Area of effect	Knockback | Fainting	Strengthened by STR, DEX, VIT	ATTACK_SKILL|NEED_TARGET|CHARGE_ATTACK|WEAPON_LIMITATION|IGNORE_BLOCK	SWORD|TWO_HANDED	tanhwan	5	4			Attack value: %.0f-%.0f	2*MinATK + (MinATK + 3*DEX + 7*STR + CON)*SkillPoint	2*MaxATK + (MaxATK + 3*DEX + 7*STR + CON)*SkillPoint			
6	WARRIOR	Life Force	Life Rays	Life Frenzy	You gather every last drop of inner strength and channel the explosive power into a single blow.	Physical melee attack	Frontal area of effect	Knockback	Strengthened by STR	ATTACK_SKILL|NEED_TARGET|WEAPON_LIMITATION|IGNORE_BLOCK	SWORD|TWO_HANDED	gihyeol	6	4			Attack value: %.0f-%.0f	(3*MinATK + (MinATK + 1.5*STR)*SkillPoint)*1.07	(3*MaxATK + (MaxATK + 1.5*STR)*SkillPoint)*1.07			
16	WARRIOR	Spirit Strike (W)	Shockwave	Tsunami Attack	Attack enemies directly.	Physical melee attack	Frontal area of effect	Knockback	Strengthened by STR, VIT	ATTACK_SKILL|CAN_CHANGE_DIRECTION|NEED_TARGET|WEAPON_LIMITATION|IGNORE_BLOCK	SWORD|TWO_HANDED	gigongcham	16	4			Attack value: %.0f-%.0f	2.3*MinATK + (MinATK*4 + 4*STR + CON)*SkillPoint	2.3*MaxATK + (MaxATK*4 + 4*STR + CON)*SkillPoint			
17	WARRIOR	Bash	Tiger Bash	Dragon Bash	Attack enemies directly.	Physical melee attack	Frontal area of effect	Strengthened by STR, VIT		ATTACK_SKILL|CAN_CHANGE_DIRECTION|WEAPON_LIMITATION|IGNORE_BLOCK	SWORD|TWO_HANDED	gyeoksan	17	4			Attack value: %.0f-%.0f	2.3*MinATK + (3*MinATK + 4*STR + 3*CON)*SkillPoint	2.3*MaxATK + (3*MaxATK + 4*STR + 3*CON)*SkillPoint			
18	WARRIOR	Stump	Lion Stump	Rhino Stump	Knock over several enemies.	Physical melee attack	Area of effect	Faint chance	Strengthened by STR, VIT, DEX	ATTACK_SKILL|STANDING_SKILL|IGNORE_BLOCK		daejin	18	4			Attack value: %.0f-%.0f	2*MinATK + (2*MinATK + 2*DEX + 2*CON + 4*STR)*SkillPoint	2*MaxATK + (2*MaxATK + 2*DEX + 2*CON + 4*STR)*SkillPoint	Faint chance: %.0f%%	(100 + 1000*SkillPoint/6)/10	
19	WARRIOR	Strong Body	Iron Body	Steel Body	Your defence increases and you don't fall down.	Buff	Reduces movement speed	No knockback at grand master level	Strengthened by STR, VIT	STANDING_SKILL		cheongeun	19	4			Defence: +%.0f	7+(40 + 0.2*str + 0.4*con)*k		Movement speed: -%.0f	1 + 9*SkillPoint	
20	WARRIOR	Sword Strike	Sword Bolt	Sword Hurl	Attack enemies directly.	Physical ranged attack	Area of effect	Knockback | Fainting	Strengthened by STR, DEX, VIT	ATTACK_SKILL|CAN_CHANGE_DIRECTION|WEAPON_LIMITATION|IGNORE_BLOCK	SWORD|TWO_HANDED	geompung	20	4			Attack value: %.0f-%.0f	2*minatk + (minatk + dex*3 + str*5 + con)*k	2*maxatk + (maxatk + dex*3 + str*5 + con)*k	Faint chance: %.0f%%	(100+k*1000/6)/10	
21	WARRIOR	Sword Orb	Sword Halo	Glorious Sword	You hit the ground with your sword.	Physical melee attack	Area of effect	Strengthened by STR, DEX, VIT		ATTACK_SKILL|STANDING_SKILL|WEAPON_LIMITATION|IGNORE_BLOCK	SWORD|TWO_HANDED	noegeom	21	4			Attack value: %.0f-%.0f	(2*MinATK + (2*MinATK + 2*DEX + 2*CON + STR*4)*SkillPoint)*1.1	(2*MaxATK + (2*MaxATK + 2*DEX + 2*CON + STR*4)*SkillPoint)*1.1			
31	ASSASSIN	Ambush	Stealth Attack	Stealth Ambush	Ambush your enemy.	Physical melee attack	Attack value increases for back hits	Strengthened by DEX, STR		ATTACK_SKILL|MELEE_ATTACK|NEED_TARGET|WEAPON_LIMITATION|IGNORE_BLOCK	DAGGER|DOUBLE_SWORD|SWORD	amseup	1	4			Attack value: %.0f-%.0f	minatk + (1.2 * minatk + 500 + dex*12)*k	maxatk + (1.2 * maxatk + 700 + dex*12)*k			
32	ASSASSIN	Fast Attack	Body Relocation	Death Strike	Approach an enemy quickly and launch a deadly attack.	Physical ranged attack	Teleport attack		Strengthened by DEX, STR	ATTACK_SKILL|NEED_TARGET|WEAPON_LIMITATION|IGNORE_BLOCK	DAGGER|DOUBLE_SWORD|SWORD	gungsin	2	4			Attack value %.0f-%.0f	(minatk + (1.6* minatk + 200 + dex*7 + str*7)*k)	(maxatk + (1.6* maxatk + 300 + dex*7 + str*7)*k)			
33	ASSASSIN	Rolling Dagger	Spinning Dagger	Dancing Dagger	Whirl around enemies with a dagger.	Physical ranged attack	Area of effect	Lasting poison attack	Strengthened by DEX, STR	ATTACK_SKILL|CAN_CHANGE_DIRECTION|WEAPON_LIMITATION|IGNORE_BLOCK	DAGGER|DOUBLE_SWORD|SWORD	charyun	3	4			Attack value: %.0f-%.0f	2*minatk + (0.5*minatk + dex*9 + str*7)*k	2*maxatk + (0.5*maxatk + dex*9 + str*7)*k	Poison chance: %.0f%%	1 + 4*k	
34	ASSASSIN	Stealth	Silent Walk	Cloaking	You can hide yourself.	Buff (on Ambush)	Stealth			STANDING_SKILL		eunhyeong	4	4			Ambush bonus damage: %.0f%%	50 * SkillPoint				
35	ASSASSIN	Poisonous Cloud	Deadly Cloud	Killing Cloud	Make poisonous clouds around the enemy and intoxicate them.	Physical ranged attack	Area of effect	Lasting poison attack	Strengthened by DEX, STR	ATTACK_SKILL|NEED_TARGET|IGNORE_BLOCK		sangong	5	4			Attack value: %.0f-%.0f	lv*2+(minatk + str*3 + dex*18)*k	lv*2+(maxatk + str*3 + dex*18)*k	Poison chance: %.0f%%	40*k	
36	ASSASSIN	Insidious Poison	Stealthy Poison	Invisible Poison	Before the attack you temporarily disappear.	Physical ranged attack	Teleport attack	Lasting poison attack	Strengthened by DEX, STR	ATTACK_SKILL|NEED_TARGET|WEAPON_LIMITATION|IGNORE_BLOCK	DAGGER|DOUBLE_SWORD|SWORD	seomjeon	6	4			Attack value: %.0f-%.0f	(lv*2+(minatk + str*3 + dex*18)*k)*1.1	(lv*2+(maxatk + str*3 + dex*18)*k)*1.1	Poison chance: %.0f%%	40*k	
46	ASSASSIN	Repetitive Shot	Multi-Shot	Massive Shot	Shoot arrows at an enemy.	Physical ranged attack	Chain attack	Knockback	Strengthened by DEX, INT	ATTACK_SKILL|NEED_TARGET|WEAPON_LIMITATION|IGNORE_BLOCK	BOW	yeonsa	16	4		2 + floor(6 * SkillPoint) 	Total attack value: %.0f-%.0f	minatk + 0.2*minatk*floor(2+k*6)+ (0.8*minatk+dex*8*ar+iq*2) *k	maxatk + 0.2*maxatk*floor(2+k*6)+ (0.8*maxatk+dex*8*ar+iq*2) *k	Arrows fired: %.0f	2 + floor(6 * SkillPoint)	
47	ASSASSIN	Arrow Shower	Dynamic Arrow	Arrow Rain	Shoot several arrows at several enemies.	Physical ranged attack	Area of effect	Opponents are slowed	Strengthened by DEX, STR	ATTACK_SKILL|FAN_RANGE|NEED_TARGET|WEAPON_LIMITATION|IGNORE_BLOCK	BOW	gwangyeok	17	4	2 + floor(6 * SkillPoint)		Attack value: %.0f-%.0f	minatk + (1.7*minatk + dex*5 + str)*k	maxatk + (1.7*maxatk + dex*5 + str)*k	Max. number of targets: %.0f	2 + floor(6 * SkillPoint)	
48	ASSASSIN	Fire Arrow	Burning Arrow	Flame Arrow	Ignite the arrow.	Physical ranged attack	Area of effect	Lasting fire damage	Strengthened by INT	ATTACK_SKILL|NEED_TARGET|WEAPON_LIMITATION|IGNORE_BLOCK	BOW	hwajo	18	4			Attack value: %.0f-%.0f	1.5*minatk + (2.6*minatk + 0.9*iq+100 )*k	1.5*maxatk + (2.6*maxatk + 0.9*iq+300 )*k	Chance of lasting fire: %.0f%%	(350+iq*4*k)/10	
49	ASSASSIN	Feather Walk	Wind Walk	God's Speed	Make your body lighter to increase movement speed. 	Buff	Increases movement speed	Explosion with area of effect	Strengthened by DEX, STR, INT	STANDING_SKILL|WEAPON_LIMITATION|IGNORE_BLOCK	BOW|DAGGER|SWORD	gyeonggong	19	4			Movement speed: +%.0f%%	60*SkillPoint		Explosive power: %.0f-%.0f	((lv*2+(3*dex+100)+str*2+iq*2)*k)	((lv*2+(3*dex+300)+str*2+iq*2)*k)
50	ASSASSIN	Poison Arrow	Toxic Arrow	Deadly Arrow	Coat the arrow with powerful poison.	Ranged attack | Area of effect	Fainting | Knockback	Lasting poison attack	Strengthened by DEX, STR, INT	ATTACK_SKILL|NEED_TARGET|WEAPON_LIMITATION|IGNORE_BLOCK	BOW	gigung	20	4			Attack value: %.0f-%.0f	minatk + (1.4*minatk + 100 + dex*7 + str*4+iq*4)*k	maxatk + (1.4*maxatk + 200 + dex*7 + str*4+iq*4)*k	Poison chance: %.0f%%	(50+dex*6*k)/10	
51	ASSASSIN	Spark	Light Beam	Lightning Blast	Inflict damage on your opponent with a beam of light.	Ranged attack | Area of effect	Lasting poison attack	Stealth	Strengthened by DEX, STR, INT	ATTACK_SKILL|STANDING_SKILL|WEAPON_LIMITATION|IGNORE_BLOCK	BOW|DAGGER|SWORD	seomgwang	21	4			Attack value: %.0f-%.0f	(MinATK + (1.2*MinATK + 100 + DEX*6 + STR*3+iq*3)*k)*1.2	(MaxATK + (1.2*MaxATK + 200 + DEX*6 + STR*3+iq*3)*k)*1.2	Poison chance: %.0f%%	(50+dex*6*k)/10	
61	SURA	Finger Strike	Burning Finger Strike	Finger Explosion	Cause a big explosion with your fingertips.	Physical melee attack	Area of effect	Opponent's defence is ignored	Strengthened by INT, STR	ATTACK_SKILL|MELEE_ATTACK|NEED_TARGET|IGNORE_BLOCK		swaeryeong	1	4			Attack value: %.0f-%.0f	minatk + 2*lv + iq*2 + (2*minatk + str*4 + iq*14) * k	maxatk + 2*lv + iq*2 + (2*maxatk + str*4 + iq*14) * k	Chance of piercing hit: %.0f%%	1 + 9*SkillPoint	
62	SURA	Dragon Swirl	Tornado Swirl	Whirlwind	Create a strong tornado to defeat several enemies.	Physical melee attack	Area of effect	Ignores opponent's evasion	Strengthened by INT, STR	ATTACK_SKILL|STANDING_SKILL|IGNORE_BLOCK		yonggwon	2	4			Attack value: %.0f-%.0f	1.1 * minatk + 2*lv + 2*iq + (1.5*minatk + str + iq*12) * k	1.1 * maxatk + 2*lv + 2*iq + (1.5*maxatk + str + iq*12) * k	Chance to ignore opponent's evasion: %.0f%%	1 + 9*SkillPoint	
63	SURA	Enchanted Blade	Enchanted Sword	Ghost Blade	Endow your blade with a powerful ghost.	Buff (can be toggled)	Increases attack value	Leeches HP	Strengthened by INT	STANDING_SKILL|TOGGLE|WEAPON_LIMITATION|IGNORE_BLOCK	SWORD	gwigeom	3	4			Attack value: +%.1f	7 + (5*iq+13)*k		Life steal: %.0f%% of damage	10*k	
64	SURA	Fear	Great Fear	Terror	Weakens the enemies skills.	Buff	Chance to dodge arrows	Reduces opponent's attack value	No attack from low-levelled monster	STANDING_SKILL		gongpo	4	4			Opponent attack value: -%.0f%%	5 + 20*SkillPoint		Opponent's misses: %.0f%%	1 + 29*SkillPoint	
65	SURA	Enchanted Armour	Stronger Enchanted Armour	Armour of Darkness	Protect your body with dark armour.	Buff	Reflects damage back at the attacker	Increases defence	Strengthened by INT	STANDING_SKILL		jumagap	5	4			Defence: +%.0f	(iq+30)*k		Reflected melee damage: %.1f%%	(iq/4+10)*k	
66	SURA	Dispel	Stronger Dispel	Dispel Attack	Remove all opponent's supporting effects.	Magic ranged attack	Area of effect	Debuff	Strengthened by INT	ATTACK_SKILL|NEED_TARGET|IGNORE_BLOCK		pabeop	6	4			Magic attack value: %.0f-%.0f	40 + 5*lv + 2*iq + (18*iq + 7*minmtk + 50)*ar*k	40 + 5*lv + 2*iq + (18*iq + 7*maxmtk + 100)*ar*k	Dispel chance: %.0f%%	50*k	
76	SURA	Dark Strike	Ghost Strike	Dark Explosion	Throw the Dark Force to damage enemies.	Magic ranged attack	Area of effect	Strengthened by INT		ATTACK_SKILL|NEED_TARGET|IGNORE_BLOCK		maryeong	16	4			Magic attack value: %.0f-%.0f	40 +5*lv + 2*iq + (20*iq + 7*minmtk + 50 )*ar*k	40 +5*lv + 2*iq + (20*iq + 7*maxmtk + 100 )*ar*k			
77	SURA	Flame Strike	Burning Strike	Flame Detonation	Burn enemies with an explosion.	Magic melee attack	AoE damage	Fire attack	Strengthened by INT, STR, VIT	ATTACK_SKILL|STANDING_SKILL|IGNORE_BLOCK		hwayeom	17	4			Magic attack value: %.0f-%.0f	5*lv + 2*iq + (20*iq + 8*mtk + str*4 + con*2 + 180 )*k	5*lv + 2*iq + (20*iq + 8*mtk + str*4 + con*2 + 200 )*k			
78	SURA	Flame Spirit	Flame Array	Flame Explosion	Call a Flame Spirit.	Magic ranged attack (can be toggled)	Area of effect	Random target	Strengthened by INT	ATTACK_SKILL|STANDING_SKILL|TOGGLE|IGNORE_BLOCK		muyeong	18	4			Magic attack value: %.0f-%.0f	30+ 2*lv + 2*iq + (18*iq + 6*minmtk + 200)*ar*k	30+ 2*lv + 2*iq + (18*iq + 6*maxmtk + 500)*ar*k			
79	SURA	Dark Protection	Dark Membrane	Protection of Dark Lord	Protects you with the Dark Force and converts physical damage into SP.	Buff	Reduces magic damage	Increases defence	Strengthened by INT	STANDING_SKILL|TOGGLE		heuksin	19	4			Damage reduction: %.0f%%	(iq*0.84)*k		Defence: +%.0f	(0.5*iq+15)*k	
80	SURA	Spirit Strike (S)	Soul Strike	Spirit Assault	Throw Dark Spirits to damage enemies.	Magic ranged attack	Area of effect	Opponents are slowed	Strengthened by INT, DEX, VIT	ATTACK_SKILL|NEED_TARGET|IGNORE_BLOCK		tusok	20	4			Magic attack value: %.0f-%.0f	40 + 2*lv + 2*iq + (2 * con + 2 * dex + 22*iq + 6*minmtk+ 180)*ar*k	40 + 2 * lv + 2*iq + (2 * con + 2 * dex + 22*iq + 6*maxmtk + 200)*ar*k	Chance of slow: %.1f%%	(333 + (300 * k))/10	
81	SURA	Dark Orb	Dark Globe	Dark Sphere	Throw Dark Orbs to damage enemies.	Magic ranged attack	Area of effect	Strengthened by INT, DEX, VIT		ATTACK_SKILL|NEED_TARGET|IGNORE_BLOCK		geomhwan	21	4			Magic attack value: %.0f-%.0f	120 + 6*lv + (5 * con + 5 * dex + 29*iq + 9*minmtk)*ar*k	120 + 6*lv + (5 * con + 5 * dex + 29*iq + 9*maxmtk)*ar*k			
91	SHAMAN	Flying Talisman	Dragon Throw	Massive Throw	Throw a talisman to damage enemies.	Magic ranged attack	Area of effect | Bell bonus	Opponents are slowed	Strengthened by INT, STR	ATTACK_SKILL|FAN_RANGE|NEED_TARGET|IGNORE_BLOCK		bipabu	1	4			Magic attack value: %.0f-%.0f	70 + 5*lv. + (18*iq+7*str+5*minmwep+50)*ar*k	70 + 5*lv + (18*iq+7*str+5*maxmwep+50)*ar*k	Chance of slow: %.1f%%	(3+iq*7*k)/10	
92	SHAMAN	Shooting Dragon	Attacking Dragon	Rising Dragon	Shoot a dragon figure to attack enemies directly.	Magic ranged attack	Knockback | Bell bonus	Lasting fire damage	Strengthened by INT, DEX	ATTACK_SKILL|NEED_TARGET|IGNORE_BLOCK		yongpa	2	4			Magic attack value: %.0f-%.0f	60 + 5*lv + (16*iq+6*dex+6*minmwep+120)*ar*k	60 + 5*lv + (16*iq+6*dex+6*maxmwep+120)*ar*k	Chance of lasting fire: %.0f%%	(100+iq*5*k)/10	
93	SHAMAN	Dragon's Roar	Dragon's Scream	Dragon's Cry	Attack enemies with a dragon figure.	Magic ranged attack	AoE damage | Bell bonus	Lasting fire damage	Strengthened by INT, STR	ATTACK_SKILL|NEED_TARGET|IGNORE_BLOCK		paeryong	3	4			Magic attack value: %.0f-%.0f	70 + 3*lv + (20*iq+3*str+10*minmwep+100)*ar*k	70 + 3*lv + (20*iq+3*str+10*maxmwep+100)*ar*k	Chance of lasting fire: %.0f%%	(100+iq*5*k)/10	
94	SHAMAN	Blessing	Heaven	Dragon	Creates a protective circle. Strengthened by INT, DEX	Buff	Can be used on group members	Resistance to melee attack.	Bonus when cast on self	STANDING_SKILL|CAN_USE_FOR_ME|NEED_TARGET|ONLY_FOR_ALLIANCE		hosin	4	4			Melee attack resistance: %.1f%%	(iq*1+15)*(2*k+0.5)/(k+1.5)				
95	SHAMAN	Reflect	Reflecting Water	Crystal Mirror	Creates a protective reflecting circle.	Buff (also for players of your kingdom)	Reflects damage back at the attacker	Bonus when cast on self	Strengthened by INT, STR	STANDING_SKILL|CAN_USE_FOR_ME|NEED_TARGET|ONLY_FOR_ALLIANCE		boho	5	4			Reflected melee damage: %.1f%%	5+(iq*0.2 +str*0.1)*k				
96	SHAMAN	Dragon's Aid	Dragon's Support	Dragon Power	Strengthens you or a group member's attack.	Buff (also for group members)	Increases chance of critical hit	Bonus when cast on self	Strengthened by INT	STANDING_SKILL|CAN_USE_FOR_ME|NEED_TARGET|ONLY_FOR_ALLIANCE		gicheon	6	4			Chance of critical hit: +%.1f%%	(iq*1+15)*(2*k+0.5)/(k+1.5)				
106	SHAMAN	Lightning Throw	Lightning Toss	Thunder Hurl	Attack with thunderbolts.	Magic ranged attack	Area of effect	Fan bonus	Strengthened by INT, DEX	ATTACK_SKILL|NEED_TARGET|IGNORE_BLOCK		noejeon	16	4			Magic attack value: %.0f-%.0f	60 + 5*lv + (8*iq+2*dex+8*minmwep+iq*5)*ar*k	60 + 5*lv + (8*iq+2*dex+8*maxmwep+iq*15)*ar*k			
107	SHAMAN	Summon Lightning	Lightning Launch	Thunder Bolt	Summon thunderbolts.	Magic ranged attack	Area of effect | Fainting	Fan bonus	Strengthened by INT, STR	ATTACK_SKILL|NEED_TARGET|IGNORE_BLOCK		byeorak	17	4			Magic attack value: %.0f-%.0f	40 + 4*lv + (13*iq+2*str+10*minmwep+iq*5)*ar*k	40 + 4*lv + (13*iq+2*str+10*maxmwep+iq*16)*ar*k	Faint chance: %.0f%%	(30+70*2*k)/10	
108	SHAMAN	Lightning Claw	Lightning Punch	Thunder Punch	Summon a thunderbolt to your fist. Fan bonus.	Magic ranged attack	Area of effect | Chain attack	Opponents are slowed	Strengthened by INT, STR	ATTACK_SKILL|NEED_TARGET|IGNORE_BLOCK		pokroe	18	4			Magic attack value: %.0f-%.0f	(50 + 5*lv + (8*iq+2*str+8*minmwep+1)*ar*k)	(50 + 5*lv + (8*iq+2*str+8*maxmwep+800)*ar*k)	Chance of slow: %.1f%%	(80+iq*5*k)/10	
109	SHAMAN	Cure	Heal	Aid of Light	Heal wounds with the aid of light.	HP recovery	Cures negative effects	Area of effect	Strengthened by INT	STANDING_SKILL|CAN_USE_FOR_ME|NEED_TARGET|ONLY_FOR_ALLIANCE		jeongeop	19	4			Restore HP: %.0f-%.0f	150+5*lv+(10*iq+6*minmwep+600)*(k*0.15)	150+5*lv+(10*iq+6*maxmwep+800)*(k*0.15)	Chance to cure negative effects: %.0f%%	20+80*k	
110	SHAMAN	Swiftness	Quickness	Speed of Wind	Run as fast as the wind. Strengthened by DEX	Increases movement speed	Reduces skill cooldown time	Can be used on group members	Bonus when cast on self	STANDING_SKILL|CAN_USE_FOR_ME|NEED_TARGET|ONLY_FOR_ALLIANCE		kwaesok	20	4			Movement speed: +%.0f%%	(dex*0.2)+35*k		Cooldown: -%.0f%%	3+33*k	
111	SHAMAN	Attack Up	Support Attack	Strengthened Attack	Strengthen a partner.	Increases attack value	Can be used on group members	Strengthened by INT, STR		STANDING_SKILL|CAN_USE_FOR_ME|NEED_TARGET|ONLY_FOR_ALLIANCE		jeungryeok	21	4			Attack value: +%.1f	10+(iq*1.8+20)*k				
112	SUPPORT	NONAME_112			Skill for party members.					PASSIVE		tongsol									
113	SUPPORT	NONAME_113			Skill for party members.					PASSIVE		tongsol									
114	SUPPORT	NONAME_114			Skill for party members.					PASSIVE		tongsol									
115	SUPPORT	NONAME_115			Skill for party members.					PASSIVE		tongsol									
116	SUPPORT	NONAME_116			Skill for party members.					PASSIVE		tongsol									
117	SUPPORT	NONAME_117			Skill for party members.					PASSIVE		tongsol									
118	SUPPORT	NONAME_118			Skill for party members.					PASSIVE		tongsol									
119	SUPPORT	NONAME_119			Skill for party members.					PASSIVE		tongsol									
121	SUPPORT	Leadership			Ability to lead group members.					PASSIVE		tongsol										
122	SUPPORT	Combo			Increase Combo attack.					CANNOT_LEVEL_UP|TOGGLE		combo										
123	SUPPORT	Fishing			Fishing knowledge.					CANNOT_LEVEL_UP		fishing										
124	SUPPORT	Mining			Ability to mine ore. 					PASSIVE		mining										
125	SUPPORT	Item Creation			Create an item.					CANNOT_LEVEL_UP|PASSIVE		making										
126	SUPPORT	Shinsoo Language			You can understand the Shinsoo language.					CANNOT_LEVEL_UP|PASSIVE		language1										
127	SUPPORT	Chunjo Language			You can understand the Chunjo language.					CANNOT_LEVEL_UP|PASSIVE		language2										
128	SUPPORT	Jinno Language			You can understand the Jinno language.					CANNOT_LEVEL_UP|PASSIVE		language3										
129	SUPPORT	Polymorph			Transform into a monster.					CANNOT_LEVEL_UP|PASSIVE		polymorph										
130	SUPPORT	Horse Riding			Ability to ride a horse.					CANNOT_LEVEL_UP|PASSIVE		riding										
131	SUPPORT	Call Horse			Summon a horse.							summon										
132	SUPPORT	Attack automatically			Attacks a selected enemy.					CANNOT_LEVEL_UP|TOGGLE		autoattack										
133	SUPPORT	Charisma			Reflects a part of the leader bonuses back to the leader.					PASSIVE		role_proficiency											
134	SUPPORT	Inspiration			Increases your leader bonuses if the leader of the group has assigned you a role.					PASSIVE		insight											
137	HORSE	Horseback Slash			Attack enemies whilst riding a horse (from lv. 50).	Riding Skill				ATTACK_SKILL|HORSE_SKILL|MOVING_SKILL|WEAPON_LIMITATION	SWORD|TWO_HANDED|DAGGER|DOUBLE_SWORD|FAN|BELL	wildattack	121	1								
138	HORSE	Horse Stump			Attack all nearby enemies. (from level 52)	Riding Skill				ATTACK_SKILL|HORSE_SKILL|SEARCH_TARGET|CHARGE_ATTACK		charge	122	1								
139	HORSE	Power Wave			Attack all enemies from your horse (from lv. 55).	Riding Skill				ATTACK_SKILL|HORSE_SKILL|WEAPON_LIMITATION	SWORD|TWO_HANDED|DAGGER|DOUBLE_SWORD|BOW|FAN|BELL	splash	123	1								
140	HORSE	Arrow Storm			Shoot arrows while you are riding. (from lv.50)	Riding Skill				ATTACK_SKILL|FAN_RANGE|NEED_TARGET|HORSE_SKILL|WEAPON_LIMITATION	BOW	wildattack	121	1	5							
151	GUILD	Dragon Eyes			Increase Maximum Dragon Ghost.					PASSIVE		yongan					Max. Dragon Ghost Increase +%.0f	k * 1400				
152	GUILD	Blood of Dragon God			Increase your maximum HP for a period of time.	Guild War Only				ONLY_FOR_GUILD_WAR		gaho	101	1			Max. HP +%.0f%%	k * 20				
153	GUILD	Benediction of Dragon God			Increase your maximum SP for a period of time.	Guild War Only				ONLY_FOR_GUILD_WAR		chukbok	102	1			Max. SP +%.0f%%	k * 20				
154	GUILD	Holy Armour			Increase your defence for a period of time.	Guild War Only				ONLY_FOR_GUILD_WAR		seonghwi	103	1			Defence +%.1f%%	k * 10				
155	GUILD	Acceleration			Increase your attack and movement speed for a period of time.	Guild War Only				ONLY_FOR_GUILD_WAR		gasok	104	1			Attack and Movement Speed +%.1f	k * 15				
156	GUILD	Wrath of the Dragon God			Increase your critical hit chance for a period of time.	Guild War Only				ONLY_FOR_GUILD_WAR		bunno	105	1			Critical Hit Chance +%.0f%%	k * 50				
157	GUILD	Casting Aid			Decrease skill cooldown times for a period of time.	Guild War Only				ONLY_FOR_GUILD_WAR		jumunsul	106	1			Cooldown Time -%.0f%%	k * 50				
180	SUPPORT	Slayer			Skill increases bonus: Strong against Humans					CANNOT_LEVEL_UP|PASSIVE		sub_skill_human					Strong against Humans +%.0f 	12*k
181	SUPPORT	Hunter			Skill increases bonus: Strong against Monsters					CANNOT_LEVEL_UP|PASSIVE		sub_skill_monster					Strong against Monsters +%.0f 	12*k
182	SUPPORT	Archaeologist			Skill increases bonus: Strong against Metin Stones					CANNOT_LEVEL_UP|PASSIVE		sub_skill_stone					Strong against Metin Stones +%.0f 	12*k
183	SUPPORT	Traveler			Skill increases bonus: Strong in Dungeons					CANNOT_LEVEL_UP|PASSIVE		sub_skill_dung					Strong in Dungeons +%.0f 	12*k
184	SUPPORT	Boss Hunter			Skill increases bonus: Strong against Bosses					CANNOT_LEVEL_UP|PASSIVE		sub_skill_boss					Strong against Bosses +%.0f 	12*k
185	SUPPORT	Wealth			Skill increases bonus: Experience Points					CANNOT_LEVEL_UP|PASSIVE		sub_skill_exp					Experience Points +%.0f%% 	16*k
186	SUPPORT	Mage			Skill increases bonus: Skill Resistance					CANNOT_LEVEL_UP|PASSIVE		sub_skill_um					Skill Resistance +%.0f%%	8*k
187	SUPPORT	Berserker			Skill increases bonus: Average Damage					CANNOT_LEVEL_UP|PASSIVE		sub_skill_sr					Average Damage +%.0f%% 	16*k
188	SUPPORT	Powerhouse			Skill increases bonus: Stats					CANNOT_LEVEL_UP|PASSIVE		sub_skill_stat					Stats +%.0f	12*k
189	SUPPORT	Healer			Skill increases bonus: Max HP					CANNOT_LEVEL_UP|PASSIVE		sub_skill_hp					Max HP +%.0f	2400*k
190	SUPPORT	Medic			Skill increases bonus: % of damage will be added to HP					CANNOT_LEVEL_UP|PASSIVE		sub_skill_do_pz					+%.0f%% of damage will be added to HP	8*k
246	SUPPORT	Precision			Increases precision					PASSIVE		hit_attribute					Precision bonus: +%.0f	0.4*k+(32*k/2)					
295	SUPPORT	MountSkill1			None					PASSIVE		petskill1										
296	SUPPORT	MountSkill2			None					PASSIVE		petskill2										
297	SUPPORT	MountSkill3			None					PASSIVE		petskill3										
298	SUPPORT	MountSkill4			None					PASSIVE		petskill4										
299	SUPPORT	MountSkill5			None					PASSIVE		petskill5				
301	SUPPORT	Vitality			None					PASSIVE		petskill1										
302	SUPPORT	Frenzy			None					PASSIVE		petskill2										
303	SUPPORT	Valor			None					PASSIVE		petskill3										
304	SUPPORT	Sharpening			None					PASSIVE		petskill4										
305	SUPPORT	Power			None					PASSIVE		petskill5										
306	SUPPORT	Omnipotence			None					PASSIVE		petskill6										
307	SUPPORT	Absorption			None					PASSIVE		petskill7										
308	SUPPORT	Rage			None					PASSIVE		petskill8										
309	SUPPORT	Armor			None					PASSIVE		petskill9										
310	SUPPORT	Penetration			None					PASSIVE		petskill10										
311	SUPPORT	Boss King			None					PASSIVE		petskill11										
312	SUPPORT	Petskill12			None					PASSIVE		petskill12				
