ACCE_ABSORB	Bonus Absorption
ACCE_COMBINE	Combination
ACCE_MAIN	Sash 1
ACCE_RESULT	Result
ACCE_SERVE	Sash 2
ACCEPT	OK
ATTACH_METIN_INFO	Do you want to use the Spirit Stone?
ATTACH_METIN_TITLE	Use Spirit Stone
AURA_MAIN	Aura Outfit
AURA_SUB	Material
CANCEL	Cancel
CHANGE_PASSWORD_CONFIRM	Confirm New Password
CHANGE_PASSWORD_NEW	New Password
CHANGE_PASSWORD_OLD	Old Password
CHANGE_PASSWORD_TITLE	Password Change
CHARACTER_ACTION	Emotion
CHARACTER_MAIN	Character
CHARACTER_QUEST	Missions
CHARACTER_SKILL	Skill
CHATTING_SETTING_CANCLE	Cancel
CHATTING_SETTING_CLEAR	Reset
CHATTING_SETTING_DEFAULT_TITLE	General
CHATTING_SETTING_DETAIL	System Settings
CHATTING_SETTING_DICE	Dice
CHATTING_SETTING_DICE_SETTING	Dice Settings
CHATTING_SETTING_EXP	Experience
CHATTING_SETTING_GOLD	Currency
CHATTING_SETTING_GUILD	Guild
CHATTING_SETTING_ITEM	Items
CHATTING_SETTING_NOTICE	Message
CHATTING_SETTING_PARTY	Group
CHATTING_SETTING_SAVE	Save
CHATTING_SETTING_SHOUT	Shout chat
CHATTING_SETTING_SYSTEM	System
CHATTING_SETTING_TALKING	General
CHATTING_SETTING_TITLE	Chat settings
CLOSE	Close
COSTUME_TITLE	Costumes
COSTUME_WINDOW_TITLE	Costumes
CREATE_ATT_GRADE	STR
CREATE_CREATE	Create
CREATE_DEX_GRADE	DEX
CREATE_HP	HP
CREATE_MAN	Man
CREATE_NAME	Name
CREATE_NEXT	Next
CREATE_PREV	Back
CREATE_SEX	Gender
CREATE_SHAPE	Shape
CREATE_SP	INT
CREATE_WOMAN	Woman
CUBE_INFO_TITLE	Refinement Handbook
CUBE_RENEWAL_TITLE	Refinement
CUBE_REQUIRE_MATERIAL	Required materials
CUBE_REQUIRE_MATERIAL_OR	or
CUBE_TITLE	Refinement Window
DO_REFINE	Refine
DRAGONSOUL_REFINE_WINDOW_TITLE	Refinement Window
DRAGONSOUL_TAP_TITLE_1	Dragon Diamond
DRAGONSOUL_TAP_TITLE_2	Dragon Ruby
DRAGONSOUL_TAP_TITLE_3	Dragon Jade
DRAGONSOUL_TAP_TITLE_4	Dragon Sapphire
DRAGONSOUL_TAP_TITLE_5	Dragon Garnet
DRAGONSOUL_TAP_TITLE_6	Dragon Onyx
DRAGONSOUL_TITLE	Dragon Stone Alchemy
EMPIRE_A	Shinsoo
EMPIRE_B	Chunjo
EMPIRE_C	Jinno
EMPIRE_EXIT	Exit
EMPIRE_NEXT	Next
EMPIRE_PREV	Back
EMPIRE_SELECT	Choose
END_TIME	Active event
EXCHANGE_TITLE	Trade
GAME_EXIT_OBSERVER	End Observer Mode
GAME_QUEST	Tasks
GAME_STAT_UP	Raise State
GAMEOPTION_TITLE	Game Options
GRADE	Class
GRADE_SELECT	Class
GUILD_BASENAME	Base Name
GUILD_BOARD_ID	Name
GUILD_BOARD_REFRESH	Refresh
GUILD_BOARD_TEXT	Message
GUILD_BUILDING_CATEGORY_TITLE	Building Units
GUILD_BUILDING_CHANGE	Change
GUILD_BUILDING_DIRECTION	Orientation
GUILD_BUILDING_GRADE	Rank
GUILD_BUILDING_INFO	Buildings and Cost Information
GUILD_BUILDING_LIST_TITLE	Building List
GUILD_BUILDING_LOG	Trunk
GUILD_BUILDING_NAME	Building name
GUILD_BUILDING_OPERATE	Operate
GUILD_BUILDING_PLY	Plywood
GUILD_BUILDING_POSITION	Position
GUILD_BUILDING_PREVIEW	Preview
GUILD_BUILDING_PRICE	Price
GUILD_BUILDING_REFRESH	Refresh
GUILD_BUILDING_STONE	Stone
GUILD_BUILDING_TITLE	Guild House Building
GUILD_CRYSTAL	Crystal
GUILD_DEPOSIT	Deposit
GUILD_DROP_RESOURCE1	Here
GUILD_DROP_RESOURCE2	Drop Resource
GUILD_GEM	Gem
GUILD_GRADE_CHANGE_GRADE_NAME	New rank name
GUILD_GRADE_NUM	Nr.
GUILD_GRADE_PERMISSION_DELETE	Remove from guild
GUILD_GRADE_PERMISSION_JOIN	May accept players to guild
GUILD_GRADE_PERMISSION_NOTICE	May compose guild messages
GUILD_GRADE_PERMISSION_SKILL	Guild skills
GUILD_GRADE_RANK	Rank
GUILD_GRADE_WRITE	Write
GUILD_INFO	Guild Information
GUILD_INFO_CUR_EXP	Experience
GUILD_INFO_DECALRE_WAR	Declare War
GUILD_INFO_ENEMY_GUILD	Enemy Guild
GUILD_INFO_ENEMY_GUILD_EMPTY	None
GUILD_INFO_LEVEL	Guild Level
GUILD_INFO_MASTER	Leader
GUILD_INFO_MASTER_VALUE	Leader
GUILD_INFO_MEMBER_AVG_LEVEL	Average Level
GUILD_INFO_MEMBER_NUM	No. of members
GUILD_INFO_NAME	Guild name
GUILD_INFO_NAME_VALUE	This is a Guild Name
GUILD_INFO_OFFER_EXP	Invest
GUILD_INFO_REST_EXP	Needed Exp.
GUILD_INFO_UPLOAD_MARK	Upload Sign
GUILD_INFO_UPLOAD_SYMBOL	Upload Flag
GUILD_MARK	Guild Sign
GUILD_MEMBER_JOB	Class
GUILD_MEMBER_KNIGHT	Combatant
GUILD_MEMBER_LEVEL	Level
GUILD_MEMBER_NAME	Name
GUILD_MEMBER_RANK	Rank
GUILD_MEMBER_SPECIFIC_GRAVITY	Invested
GUILD_METIN_STONE	Spirit Stone
GUILD_MINENAL	Mineral
GUILD_MONEY	Yang
GUILD_NAME	Guild
GUILD_RESOURCE_INFO	Resources Information
GUILD_SKILL_ACTIVE	Active
GUILD_SKIlL_HEAL_GSP	Win back Power
GUILD_SKILL_PASSIVE	Passive
GUILD_SKILL_POWER	Energy
GUILD_SKILL_STATE	Skills of the Guild
GUILD_WAR_ACCEPT	Accept War Declaration
GUILD_WAR_BATTLE_TYPE	Battle Type
GUILD_WAR_CTF	Flag
GUILD_WAR_DECLARE	Declare Guild War
GUILD_WAR_ENEMY	Enemy
GUILD_WAR_NORMAL	Field
GUILD_WAR_WARP	Arena
GUILD_WAR_WIN	Rounds
GUILD_WATER	Water
GUILD_WATER_STONE	Waterstone
GUILD_WITHDRAW	Take
HELP_ATTACK	Activates single attacks per mouse click.
HELP_ATTACK_KEY	Attack: left mouse button or space bar
HELP_CHANGE_PK_MODE	Change attack mode: change setting of left mouse button
HELP_CHARACTER_BUTTON1	(Character Window, Inventory Window,
HELP_CHARACTER_BUTTON2	List of Friends and Options)
HELP_CONTROL_CAMERA_BY_MIDDLEBUTTON	Default Camera View: middle mouse button
HELP_CONTROL_CAMERA_BY_RIGHTBUTTON	Alternative Camera View: assign to right or left mouse
HELP_EXP	Experience
HELP_FURY	Ingame Item Shop
HELP_GUILD_WINDOW	Open Guild Window: Alt + G
HELP_HELP	Display help: H
HELP_HP	Hit Points (HP)
HELP_MESSENGER_WINDOW	Open Friends List: Alt + M
HELP_MOUSE_LEFT	Function of the Left Mouse button
HELP_MOUSE_RIGHT	Function of the Right Mouse button
HELP_MOVE_KEY	Panel: W, A, S, D or arrow keys
HELP_OPEN_CHARACTER	Open character window: C
HELP_OPEN_CHAT	Open chat window: Enter
HELP_OPEN_INVENTORY	Open inventory window: I
HELP_OPEN_LOG	Open Chatlog: L
HELP_OPEN_MINIMAP	Open mini map: Shift + M
HELP_OPEN_QUEST	Open Task Window: N
HELP_OPEN_SKILL	Open Skill Window: V
HELP_OPEN_WHISPER	Open Whisper Window: Shift + Enter
HELP_OPEN_ZONEMAP	Open Large Map: M
HELP_PICK_ITEM	Collect Items: ` or Z or left mouse button
HELP_QUICKSLOT	Fast Access Fields
HELP_SCREEN_CAPTURE	Save Screenshot: Print (will be saved in file "Metin2\screenshot")
HELP_SHOW_ALL_NAME	Display Names: Alt
HELP_SP	Spell Points (SP)
HELP_SYSTEM_BUTTON	System buttons
INVENTORY_PAGE_BUTTON_TOOLTIP_1	1st Inventory
INVENTORY_PAGE_BUTTON_TOOLTIP_2	2nd Inventory
INVENTORY_PAGE_BUTTON_TOOLTIP_3	3rd Inventory
INVENTORY_PAGE_BUTTON_TOOLTIP_4	4th Inventory
INVENTORY_TITLE	Inventory
ITEM_MALL	Item Shop
KEYCHANGE_ACTION_WINDOW	Actions
KEYCHANGE_ATTACK	Attack
KEYCHANGE_AUTO_WINDOW	Auto-Hunting
KEYCHANGE_AUTORUN	Autorun
KEYCHANGE_BASEACTION	Standard Keys
KEYCHANGE_CAM_DOWN1	Camera (down)
KEYCHANGE_CAM_DOWN2	Camera (down)
KEYCHANGE_CAM_LEFT1	Camera (left)
KEYCHANGE_CAM_LEFT2	Camera (left)
KEYCHANGE_CAM_RIGHT1	Camera (right)
KEYCHANGE_CAM_RIGHT2	Camera (right)
KEYCHANGE_CAM_UP1	Camera (up)
KEYCHANGE_CAM_UP2	Camera (up)
KEYCHANGE_CAM_ZOOM_IN1	Camera (zoom in)
KEYCHANGE_CAM_ZOOM_IN2	Camera (zoom in)
KEYCHANGE_CAM_ZOOM_OUT1	Camera (zoom out)
KEYCHANGE_CAM_ZOOM_OUT2	Camera (zoom out)
KEYCHANGE_CHAT_WINDOW	Chat log
KEYCHANGE_DDS_WINDOW	DSS
KEYCHANGE_DOWN1	Backwards
KEYCHANGE_DOWN2	Backwards
KEYCHANGE_EMOTION1	Emotion (Sad)
KEYCHANGE_EMOTION2	Emotion (Yang)
KEYCHANGE_EMOTION3	Emotion (Music)
KEYCHANGE_EMOTION4	Emotion (Heart)
KEYCHANGE_EMOTION5	Emotion (Hearts)
KEYCHANGE_EMOTION6	Emotion (Bomb)
KEYCHANGE_EMOTION7	Emotion (Idea)
KEYCHANGE_EMOTION8	Emotion (Storm)
KEYCHANGE_EMOTION9	Emotion (Sorry)
KEYCHANGE_GUILD_WINDOW	Guild
KEYCHANGE_HELP_WINDOW	Help
KEYCHANGE_IMPOSSIBLE_CHANGE	[CTRL], [ALT], [SHIFT] are not allowed here!
KEYCHANGE_INTERFACE	Window
KEYCHANGE_INVENTORY_WINDOW	Inventory
KEYCHANGE_KEY_SETTING	Keyboard Settings
KEYCHANGE_LEFT1	Left
KEYCHANGE_LEFT2	Left
KEYCHANGE_MESSENGER_WINDOW	Friends
KEYCHANGE_MINIMAP_MINER	Minimap (-)
KEYCHANGE_MINIMAP_PLUS	Minimap (+)
KEYCHANGE_MINIMAP_WINDOW	Large map
KEYCHANGE_MONSTER_CARD_WINDOW	Monster Card
KEYCHANGE_PARTY_MATCH_WINDOW	Group Search
KEYCHANGE_QUEST_SCROLL_ONOFF	Quest scrolls
KEYCHANGE_QUEST_WINDOW	Quests
KEYCHANGE_QUICKSLOT1	Level 1
KEYCHANGE_QUICKSLOT2	Level 2
KEYCHANGE_QUICKSLOT3	Level 3
KEYCHANGE_QUICKSLOT4	Level 4
KEYCHANGE_RIDE	Mount
KEYCHANGE_RIDE_BYE	Dismiss horse
KEYCHANGE_RIDE_HORSE	Mount
KEYCHANGE_RIDE_PEED	Feed horse
KEYCHANGE_RIGHT1	Right
KEYCHANGE_RIGHT2	Right
KEYCHANGE_ROOT1	Pick up
KEYCHANGE_ROOT2	Pick up
KEYCHANGE_SAVE	Save
KEYCHANGE_SCREENSHOT	Screenshot
KEYCHANGE_SHOW_NAME	Show names
KEYCHANGE_SKILL_WINDOW	Skills
KEYCHANGE_SLOT1	Slot 1
KEYCHANGE_SLOT2	Slot 2
KEYCHANGE_SLOT3	Slot 3
KEYCHANGE_SLOT4	Slot 4
KEYCHANGE_SLOT5	Slot 5
KEYCHANGE_SLOT6	Slot 6
KEYCHANGE_SLOT7	Slot 7
KEYCHANGE_SLOT8	Slot 8
KEYCHANGE_SLOT_KET	Quick Slots
KEYCHANGE_STATUS_WINDOW	Character
KEYCHANGE_UP1	Forwards
KEYCHANGE_UP2	Forwards
LANGUAGE_EN	English
LOAD_ERROR	The File is damaged. Please install new. Press ESC now.
LOGIN_CONNECT	Connect
LOGIN_CONNECTING	You will be connected to the Server
LOGIN_DEFAULT_SERVERADDR	Servername, Channel 1
LOGIN_EXIT	Exit
LOGIN_ID	Username
LOGIN_PASSWORD	Password
LOGIN_SELECT_BUTTON	Choose
LOGIN_SELECT_EXIT	Exit
LOGIN_SELECT_TITLE	Choose Server
MALL_PASSWORD_TITLE	Password
MALL_TITLE	Item Shop Storeroom
MARKLIST_REFRESH	Refresh
MARKLIST_TITLE	Register Guild Sign
MESSAGE	This is a Message
MESSENGER_ADD_FRIEND	Add friend
MESSENGER_DELETE_FRIEND	Delete
MESSENGER_OPEN_GUILD	Open Guild Window
MESSENGER_TITLE	Friends
MESSENGER_WHISPER	Whisper
MINI_GAME_RUMI_DISCARD_TEXT	Secure Mode
MINI_GAME_RUMI_EXIT	End
MINI_GAME_RUMI_LBUTTON_DESC	Left-click to add card
MINI_GAME_RUMI_RBUTTON_DESC	Right-click to discard card
MINI_GAME_RUMI_SCORE	Score
MINI_GAME_RUMI_START_TEXT	Start
MINI_GAME_RUMI_TITLE	Okey Card Game
MINIMIZE	Minimize
MOUSEBUTTON_ATTACK	Attack
MOUSEBUTTON_AUTO_ATTACK	Attack automatically
MOUSEBUTTON_CAMERA	Camera
MOUSEBUTTON_SKILL	Skills
MUSICLIST_TITLE	Music Choices
NO	No
OK	OK
OPTION_ALWAYS_SHOW_NAME	Name
OPTION_ALWAYS_SHOW_NAME_OFF	Limited
OPTION_ALWAYS_SHOW_NAME_ON	Always
OPTION_BLOCK	Block
OPTION_BLOCK_EXCHANGE	Trade
OPTION_BLOCK_FRIEND	Friends
OPTION_BLOCK_GUILD	Guild
OPTION_BLOCK_PARTY	Group
OPTION_BLOCK_PARTY_REQUEST	Request
OPTION_BLOCK_WHISPER	Whisper
OPTION_CAMERA_DISTANCE	Camera
OPTION_CAMERA_DISTANCE_LONG	Far
OPTION_CAMERA_DISTANCE_SHORT	Close
OPTION_DELETE_MOBILE_BUTTON	Delete Cell Phone Number
OPTION_EFFECT	Hit Info
OPTION_FOG	Fog
OPTION_FOG_DENSE	Dense
OPTION_FOG_LIGHT	Light
OPTION_FOG_MIDDLE	Middle
OPTION_INPUT_MOBILE_BUTTON	Enter Cell Phone Number
OPTION_MOB_INFO	Monster info
OPTION_MOB_INFO_AGGR	Aggressive
OPTION_MOB_INFO_LEVEL	Level
OPTION_MOBILE	Cell Phone
OPTION_MUSIC	Music
OPTION_MUSIC_CHANGE	Change
OPTION_MUSIC_DEFAULT_THEMA	Standard Music of Metin2
OPTION_NAME_COLOR	Name Color
OPTION_NAME_COLOR_EMPIRE	Kingdom Color
OPTION_NAME_COLOR_NORMAL	Normal
OPTION_NIGHT_MODE	Night
OPTION_NIGHT_MODE_OFF	Off
OPTION_NIGHT_MODE_ON	On
OPTION_PVPMODE	PvP Mode
OPTION_PVPMODE_FREE	Free
OPTION_PVPMODE_FREE_TOOLTIP	You are allowed to attack all players.
OPTION_PVPMODE_GUILD	Guild
OPTION_PVPMODE_GUILD_TOOLTIP	You are allowed to attack all players but your Guild members.
OPTION_PVPMODE_PEACE	Peace
OPTION_PVPMODE_PEACE_TOOLTIP	You cannot attack players from your kingdom.
OPTION_PVPMODE_REVENGE	Hostile
OPTION_PVPMODE_REVENGE_TOOLTIP	You can only attack those who have another Ethos.
OPTION_SALESTEXT	Shop name
OPTION_SALESTEXT_VIEW_OFF	Hide
OPTION_SALESTEXT_VIEW_ON	Show
OPTION_SNOW_MODE	Snowfall
OPTION_SNOW_MODE_OFF	Off
OPTION_SNOW_MODE_ON	On
OPTION_SNOW_TEXTURE_MODE	Snow
OPTION_SNOW_TEXTURE_MODE_OFF	Off
OPTION_SNOW_TEXTURE_MODE_ON	On
OPTION_SOUND	Sound Effects
OPTION_TARGET_BOARD	Target Menu
OPTION_TARGET_BOARD_NO_VIEW	Close
OPTION_TARGET_BOARD_VIEW	Show
OPTION_TITLE	Options
OPTION_VIEW_CHAT	Chat Line
OPTION_VIEW_CHAT_OFF	Hide
OPTION_VIEW_CHAT_ON	Show
PARTY_MEMBER_INFO_NAME	Name of the Group member
PASSWORD_DESC_1	Enter your password
PASSWORD_DESC_2	to open the storeroom.
PASSWORD_DESC_3	Already changed your password?
PASSWORD_DESC_4	If not, your password will be '000000'.
PASSWORD_DESC_5	Change your password in storage.
PASSWORD_TITLE	Saving Password
PICK_MONEY_TITLE	Divide
PREMIUM_PRIVATE_SHOP	Personal Premium Shop
PREMIUM_PRIVATE_SHOP_SHOP_CLOSE_BUTTON	Close shop
PREMIUM_PRIVATE_SHOP_TITLE	Personal Shop
PRIVATE_SHOP_CLOSE_BUTTON	Close shop
PRIVATE_SHOP_TITLE	Open private shop
PRIVATESHOPSEARCH_BUY	Buy
PRIVATESHOPSEARCH_COUNT	Quantity
PRIVATESHOPSEARCH_ITEMNAME	Name
PRIVATESHOPSEARCH_ITEMTYPE	Items
PRIVATESHOPSEARCH_JOB	Class
PRIVATESHOPSEARCH_LEVEL	Level
PRIVATESHOPSEARCH_PRICE	Price
PRIVATESHOPSEARCH_REFINE	Item Level
PRIVATESHOPSEARCH_SEARCH	Search
PRIVATESHOPSEARCH_SEARCH_BAR	Search
PRIVATESHOPSEARCH_SELECT	Select
PRIVATESHOPSEARCH_SELLER	Seller
REFINE_INFO	Chance to upgrade successfully: 100%
REFINE_TTILE	Upgrades
RESTART_HERE	Restart here
RESTART_TOWN	Restart in the City
SAFE_CHANGE_PASSWORD	Change Password
SAFE_TITLE	Storeroom
SELECT_ATT_GRADE	STR
SELECT_CREATE	Create
SELECT_DELETE	Delete
SELECT_DEX_GRADE	DEX
SELECT_EMPIRE_NAME	Name of Kingdom
SELECT_EXIT	Close
SELECT_HP	HP
SELECT_LEVEL	Level
SELECT_METIN_STONE_TITLE	Select Spirit Stone
SELECT_NAME	Name
SELECT_NO_GUILD	No Guild
SELECT_PLAYTIME	Playtime
SELECT_SELECT	Start
SELECT_SP	SP
SELECT_TITLE	Choose Title
SHOP_BUY	Buy
SHOP_SELL	Sell
SHOP_TITLE	Shop
STEP	Clarity grade
STEP_SELECT	Clarity grade
STRENGTH	Strengthen
STRENGTH_SELECT	Level
SYSTEM_CHANGE	Change Character
SYSTEM_EXIT	Exit Game
SYSTEM_HELP	Help
SYSTEM_LOGOUT	Log Out
SYSTEM_MALL	Item Shop
SYSTEM_MOVE_CHANNEL	Change Channel
SYSTEM_OPTION	System Options
SYSTEMOPTION_TITLE	System Options
TASKBAR_CHARACTER	Character [C/V/B/N]
TASKBAR_DISABLE	Deactivated
TASKBAR_DRAGON_SOUL	Dragon Stone Alchemy
TASKBAR_EXPAND	Expand window
TASKBAR_INVENTORY	Inventory [I]
TASKBAR_MESSENGER	Friends [Alt+M]
TASKBAR_MONEY_EXPAND	Money
TASKBAR_NEXT_QUICKSLOT	Next Fast Access Field [Shift+Number, Alt]
TASKBAR_PREV_QUICKSLOT	Previous Fast Access Field [Shift+Number]
TASKBAR_SYSTEM	Options[ESC]
WHISPER_BAN	Block
WHISPER_NAME	Whisper
WHISPER_SEND	Send
YES	Yes
ZONE_MAP	Large Map

VOICE_CHAT_TOOLTIP_CLICK_TO_LOCK	Click to lock
VOICE_CHAT_TOOLTIP_CLICK_TO_UNLOCK	Click to unlock
OPTION_VSYNC	VSync
OPTION_VSYNC_ON	On
OPTION_VSYNC_OFF	Off
OPTION_RESIZE_WINDOW	Resizable window
OPTION_RESIZE_WINDOW_ON	On
OPTION_RESIZE_WINDOW_OFF	Off
OPTION_FPS_LIMIT	FPS limit
OPTION_FPS_UNLIMITED	Unlimited
