import localeInfo

ROOT = "kowal/game/warpwindow/"

window = {
	"name" : "DungeonTrackWindow",
	"x" : 35,
	"y" : 0,
	"style" : ("movable", "float",),
	"width" : 605,
	"height" : 477,
	"children" :
	(
		{
			"name" : "board",
			"type" : "expanded_image",
			"x" : 35,
			"y" : 0,
			"image" : ROOT + "dungeon_info/bg.png",
		},
		# Dungeon Page
		{
			"name" : "dungeon_page",
			"type" : "window",
			"x" : 35,
			"y" : 0,
			"width" : 563,
			"height" : 477,
			"children" :
			(
				{
					"name" : "list_window",
					"type" : "window",
					"x" : 8,
					"y" : 36,
					"width" : 353,
					"height" : 434,
				},
				{
					"name" : "scrollbar",
					"type" : "modern_scrollbar",
					"x" : 364,
					"y" : 36,
					"width": 6,
					"size": 434,
					"content_height": 433,
					"smooth": 1,
					"scroll_step": 0.30,
				},
				{
					"name" : "right_bg",
					"type" : "image",
					"x" : 372,
					"y" : 36,
					"image" : ROOT + "dungeon_info/right_bg.png",
					"children" :
					(
						{
							"name" : "title",
							"type" : "text",
							"x" : 10,
							"y" : -204,
							"text" : "Unknown Dungeon",
							"all_align" : "center",
							"outline" : 1,
							"fontname":"Verdana:14b",
							"color":0xFFb39d8a,
						},
						{
							"name" : "wiki_btn",
							"type" : "button",
							"x" : 4,
							"y" : 4,
							"default_image" : ROOT + "dungeon_info/wiki_btn_norm.png",
							"over_image" : ROOT + "dungeon_info/wiki_btn_hover.png",
							"down_image" : ROOT + "dungeon_info/wiki_btn_down.png",
						},
						{
							"name" : "level_info",
							"type" : "text",
							"x" : 12,
							"y" : 41,
							"text" : localeInfo.DUNGEON_TRACK_LEVEL_INFO,
							"fontname" : "Verdana:14",
							"color" : 0xFFa4a4a4,
						},
						{
							"name" : "level_text",
							"type" : "text",
							"x" : 178,
							"y" : 41,
							"text" : "0",
							"text_horizontal_align" : "right",
							"fontname" : "Verdana:14",
							"color" : 0xFFd0cecc,
						},
						{
							"name" : "cooldown_info",
							"type" : "text",
							"x" : 12,
							"y" : 61,
							"text" : localeInfo.DUNGEON_TRACK_COOLDOWN_INFO,
							"fontname" : "Verdana:14",
							"color" : 0xFFa4a4a4,
						},
						{
							"name" : "cooldown_text",
							"type" : "text",
							"x" : 178,
							"y" : 61,
							"text" : "0s",
							"text_horizontal_align" : "right",
							"fontname" : "Verdana:14",
							"color" : 0xFFd0cecc,
						},
						{
							"name" : "daily_limit_info",
							"type" : "text",
							"x" : 12,
							"y" : 81,
							"text" : localeInfo.DUNGEON_TRACK_DAILY_LIMIT_INFO,
							"fontname" : "Verdana:14",
							"color" : 0xFFa4a4a4,
						},
						{
							"name" : "daily_limit_text",
							"type" : "text",
							"x" : 178,
							"y" : 81,
							"text" : "0/0",
							"text_horizontal_align" : "right",
							"fontname" : "Verdana:14",
							"color" : 0xFFd0cecc,
						},
						{
							"name" : "ticket_slot",
							"type" : "image",
							"x" : 77,
							"y" : 177,
							"image" : ROOT + "dungeon_info/ticket_item_bg.png",
						},
						{
							"name" : "ticket_info",
							"type" : "text",
							"x" : 0,
							"y" : -69,
							"text" : localeInfo.DUNGEON_TRACK_TICKET_INFO,
							"all_align" : "center",
							"outline" : 1,
							"fontname" : "Verdana:14b",
							"color" : 0xFFb39d8a,
						},
						{
							"name" : "shop_btn",
							"type" : "button",
							"x" : 137,
							"y" : 185,
							"default_image" : ROOT + "dungeon_info/buy_ticket_norm.png",
							"over_image" : ROOT + "dungeon_info/buy_ticket_hover.png",
							"down_image" : ROOT + "dungeon_info/buy_ticket_down.png",
						},
						{
							"name" : "checkbox",
							"type" : "button",
							"x" : 5,
							"y" : 371,
							"default_image" : ROOT + "dungeon_info/checkbox_empty.png",
							"over_image" : ROOT + "dungeon_info/checkbox_empty.png",
							"down_image" : ROOT + "dungeon_info/checkbox_empty.png",
						},
						{
							"name" : "check_info",
							"type" : "text",
							"x" : 24,
							"y" : 371,
							"text" : localeInfo.DUNGEON_TRACK_CHECKBOX,
							"outline" : 1,
							"fontname" : "Verdana:12",
							"color" : 0xFFb39d8a,
						},
						{
							"name" : "personal_info",
							"type" : "text",
							"x" : 0,
							"y" : 33,
							"text" : localeInfo.DUNGEON_TRACK_PERSONAL_STATISTICS,
							"all_align" : "center",
							"outline" : 1,
							"fontname" : "Verdana:14b",
							"color" : 0xFFb39d8a,
						},
						{
							"name" : "completed_rank",
							"type" : "button",
							"x" : 20,
							"y" : 332,
							"default_image" : ROOT + "dungeon_info/ranking_btn_norm.png",
							"over_image" : ROOT + "dungeon_info/ranking_btn_hover.png",
							"down_image" : ROOT + "dungeon_info/ranking_btn_down.png",
						},
						{
							"name" : "completed_info",
							"type" : "text",
							"x" : 45,
							"y" : 275,
							"text" : localeInfo.DUNGEON_TRACK_COMPLETED,
							"text_horizontal_align" : "center",
							"color" : 0xFFa4a4a4,
						},
						{
							"name" : "completed_text",
							"type" : "text",
							"x" : 43,
							"y" : 314,
							"text" : "0",
							"text_horizontal_align" : "center",
							"color" : 0xFFa4a4a4,
						},
						{
							"name" : "fast_rank",
							"type" : "button",
							"x" : 122,
							"y" : 332,
							"default_image" : ROOT + "dungeon_info/ranking_btn_norm.png",
							"over_image" : ROOT + "dungeon_info/ranking_btn_hover.png",
							"down_image" : ROOT + "dungeon_info/ranking_btn_down.png",
						},
						{
							"name" : "fast_info",
							"type" : "text",
							"x" : 146,
							"y" : 275,
							"text" : localeInfo.DUNGEON_TRACK_FASTEST,
							"text_horizontal_align" : "center",
							"color" : 0xFFa4a4a4,
						},
						{
							"name" : "fast_text",
							"type" : "text",
							"x" : 145,
							"y" : 314,
							"text" : "0s",
							"text_horizontal_align" : "center",
							"color" : 0xFFa4a4a4,
						},
						{
							"name" : "damage_rank",
							"type" : "button",
							"x" : 71,
							"y" : 332,
							"default_image" : ROOT + "dungeon_info/ranking_btn_norm.png",
							"over_image" : ROOT + "dungeon_info/ranking_btn_hover.png",
							"down_image" : ROOT + "dungeon_info/ranking_btn_down.png",
						},
						{
							"name" : "damage_info",
							"type" : "text",
							"x" : 96,
							"y" : 275,
							"text" : localeInfo.DUNGEON_TRACK_DMG,
							"text_horizontal_align" : "center",
							"color" : 0xFFa4a4a4,
						},
						{
							"name" : "damage_text",
							"type" : "text",
							"x" : 94,
							"y" : 314,
							"text" : "0",
							"text_horizontal_align" : "center",
							"color" : 0xFFa4a4a4,
						},
						{
							"name" : "enter_btn",
							"type" : "button",
							"x" : 51,
							"y" : 397,
							"tooltip_text" : localeInfo.DUNGEON_TRACK_TELEPORT_ENTER,
							"default_image" : ROOT + "dungeon_info/enter_btn_norm.png",
							"over_image" : ROOT + "dungeon_info/enter_btn_hover.png",
							"down_image" : ROOT + "dungeon_info/enter_btn_down.png",
						},
					),
				},
			),
		},
		## Normal Map Page
		{
			"name" : "map_page",
			"type" : "window",
			"x" : 35,
			"y" : 0,
			"width" : 563,
			"height" : 477,
			"children" :
			(
				{
					"name" : "map_right_bg",
					"type" : "image",
					"x" : 8,
					"y" : 67,
					"image" : ROOT + "maps/maps_bg.png",
				},
				{
					"name" : "buttons_bg",
					"type" : "image",
					"x" : 8,
					"y" : 35,
					"image" : ROOT + "maps/buttons_bg.png",
				},
				{
					"name" : "low_maps_btn",
					"type" : "button",
					"x" : 9,
					"y" : 37,
					"default_image" : ROOT + "maps/btn_map_norm.png",
					"over_image" : ROOT + "maps/btn_map_hover.png",
					"down_image" : ROOT + "maps/btn_map_down.png",
					"children":
					(
						{
							"name" : "low_maps_text",
							"type" : "text",
							"x" : 70,
							"y" : 6,
							"text" : localeInfo.WARP_WINDOW_MAPS_LOW,
							"fontname":"Verdana:13b",
							"text_horizontal_align" : "center",
							"outline" : 1,
							"color" : 0xFFab9071,
						},
					),
				},
				{
					"name" : "high_maps_btn",
					"type" : "button",
					"x" : 149,
					"y" : 37,
					"default_image" : ROOT + "maps/btn_map_norm.png",
					"over_image" : ROOT + "maps/btn_map_hover.png",
					"down_image" : ROOT + "maps/btn_map_down.png",
					"children":
					(
						{
							"name" : "high_maps_text",
							"type" : "text",
							"x" : 70,
							"y" : 6,
							"text" : localeInfo.WARP_WINDOW_MAPS_HIGH,
							"fontname":"Verdana:13b",
							"text_horizontal_align" : "center",
							"outline" : 1,
							"color" : 0xFFab9071,
						},
					),
				},
				{
					"name" : "special_maps_btn",
					"type" : "button",
					"x" : 289,
					"y" : 37,
					"default_image" : ROOT + "maps/btn_map_norm.png",
					"over_image" : ROOT + "maps/btn_map_hover.png",
					"down_image" : ROOT + "maps/btn_map_down.png",
					"children":
					(
						{
							"name" : "special_maps_text",
							"type" : "text",
							"x" : 70,
							"y" : 6,
							"text" : localeInfo.WARP_WINDOW_MAPS_SPECIAL,
							"fontname":"Verdana:13b",
							"text_horizontal_align" : "center",
							"outline" : 1,
							"color" : 0xFFab9071,
						},
					),
				},
				{
					"name" : "SearchFieldContainer",
					"type" : "window",
					"x" : 432,
					"y" : 36,
					"width" : 132,
					"height" : 29,
				},
				{
					"name" : "map_list_window",
					"type" : "window",
					"x" : 10,
					"y" : 69,
					"width" : 544,
					"height" : 400,
				},
				{
					"name" : "map_scrollbar",
					"type" : "modern_scrollbar",
					"x" : 555,
					"y" : 70,
					"width": 6,
					"size": 400,
					"content_height": 400,
					"smooth": 1,
					"scroll_step": 0.30,
				},
			),
		},
		{
			"name" : "titlebar",
			"type" : "titlebar",
			"style" : ("attach",),
			"x" : 19+35,
			"y" : 11,
			"width" : 533,
			"color" : "red",
			"children" :
			(
				{
					"name" : "TitleName",
					"type" : "text",
					"x" : 0,
					"y" : -3,
					"text" : localeInfo.DUNGEON_TRACK_TITLE_DUNGEONS,
					"all_align" : "center",
				},
			),
		},
		{
			"name" : "clear_btn",
			"type" : "button",
			"x" : 73,
			"y" : 11,
			"default_image" : "kowal/game/guild/guild_logs/refresh_btn_norm.png",
			"over_image" : "kowal/game/guild/guild_logs/refresh_btn_hover.png",
			"down_image" : "kowal/game/guild/guild_logs/refresh_btn_down.png",
		},
	),
}