import uiScriptLocale

ICON_PATH = "kowal/game/animated_icons"

window = {
	"name" : "IconsWindow",
	"x" : SCREEN_WIDTH - 580,
	"y" : 0,
	"width" : 400,
	"height" : 120,
	"children" :
	(
		{
			"name" : "expander",
			"type" : "button",
			"x":168,
			"y":1,
			"default_image" : "d:/ymir work/ui/btn_expand_normal.png",
			"over_image" : "d:/ymir work/ui/btn_expand_over.png",
			"down_image" : "d:/ymir work/ui/btn_expand_down.png",
		},
		{
			"name" : "ItemShopButtonAni",
			"type" : "ani_image",
			"x":308,
			"y":20,
			"delay" : 3,
			"images" :
			(
				ICON_PATH + "/itemshop/frame_0001.png",
				ICON_PATH + "/itemshop/frame_0002.png",
				ICON_PATH + "/itemshop/frame_0003.png",
				ICON_PATH + "/itemshop/frame_0004.png",
				ICON_PATH + "/itemshop/frame_0005.png",
				ICON_PATH + "/itemshop/frame_0006.png",
				ICON_PATH + "/itemshop/frame_0007.png",
				ICON_PATH + "/itemshop/frame_0008.png",
				ICON_PATH + "/itemshop/frame_0009.png",
				ICON_PATH + "/itemshop/frame_0010.png",
				ICON_PATH + "/itemshop/frame_0011.png",
				ICON_PATH + "/itemshop/frame_0012.png",
				ICON_PATH + "/itemshop/frame_0013.png",
				ICON_PATH + "/itemshop/frame_0014.png",
				ICON_PATH + "/itemshop/frame_0015.png",
				ICON_PATH + "/itemshop/frame_0016.png",
				ICON_PATH + "/itemshop/frame_0017.png",
				ICON_PATH + "/itemshop/frame_0018.png",
				ICON_PATH + "/itemshop/frame_0019.png",
				ICON_PATH + "/itemshop/frame_0020.png",
				ICON_PATH + "/itemshop/frame_0021.png",
				ICON_PATH + "/itemshop/frame_0022.png",
				ICON_PATH + "/itemshop/frame_0023.png",
				ICON_PATH + "/itemshop/frame_0024.png",
				ICON_PATH + "/itemshop/frame_0025.png",
				ICON_PATH + "/itemshop/frame_0026.png",
				ICON_PATH + "/itemshop/frame_0027.png",
				ICON_PATH + "/itemshop/frame_0028.png",
				ICON_PATH + "/itemshop/frame_0029.png",
				ICON_PATH + "/itemshop/frame_0030.png",
				ICON_PATH + "/itemshop/frame_0031.png",
				ICON_PATH + "/itemshop/frame_0032.png",
				ICON_PATH + "/itemshop/frame_0033.png",
				ICON_PATH + "/itemshop/frame_0034.png",
				ICON_PATH + "/itemshop/frame_0035.png",
				ICON_PATH + "/itemshop/frame_0036.png",
				ICON_PATH + "/itemshop/frame_0037.png",
				ICON_PATH + "/itemshop/frame_0038.png",
				ICON_PATH + "/itemshop/frame_0039.png",
				ICON_PATH + "/itemshop/frame_0040.png",
				ICON_PATH + "/itemshop/frame_0041.png",
				ICON_PATH + "/itemshop/frame_0042.png",
				ICON_PATH + "/itemshop/frame_0043.png",
				ICON_PATH + "/itemshop/frame_0044.png",
				ICON_PATH + "/itemshop/frame_0045.png",
				ICON_PATH + "/itemshop/frame_0046.png",
				ICON_PATH + "/itemshop/frame_0047.png",
				ICON_PATH + "/itemshop/frame_0048.png",
				ICON_PATH + "/itemshop/frame_0049.png",
				ICON_PATH + "/itemshop/frame_0050.png",
				ICON_PATH + "/itemshop/frame_0051.png",
				ICON_PATH + "/itemshop/frame_0052.png",
				ICON_PATH + "/itemshop/frame_0053.png",
				ICON_PATH + "/itemshop/frame_0054.png",
				ICON_PATH + "/itemshop/frame_0055.png",
				ICON_PATH + "/itemshop/frame_0056.png",
				ICON_PATH + "/itemshop/frame_0057.png",
				ICON_PATH + "/itemshop/frame_0058.png",
				ICON_PATH + "/itemshop/frame_0059.png",
				ICON_PATH + "/itemshop/frame_0060.png",
				ICON_PATH + "/itemshop/frame_0061.png",
				ICON_PATH + "/itemshop/frame_0062.png",
				ICON_PATH + "/itemshop/frame_0063.png",
				ICON_PATH + "/itemshop/frame_0064.png",
				ICON_PATH + "/itemshop/frame_0065.png",
				ICON_PATH + "/itemshop/frame_0066.png",
				ICON_PATH + "/itemshop/frame_0067.png",
				ICON_PATH + "/itemshop/frame_0068.png",
				ICON_PATH + "/itemshop/frame_0069.png",
				ICON_PATH + "/itemshop/frame_0070.png",
				ICON_PATH + "/itemshop/frame_0071.png",
				ICON_PATH + "/itemshop/frame_0072.png",
			),
		},
		{
			"name" : "ItemShopButton",
			"type" : "button",
			"x":291,
			"y":20,
			"default_image" : "kowal/is_1.png",
			"over_image" : "kowal/is_2.png",
			"down_image" : "kowal/is_3.png",
		},
		{
			"name" : "BattlepassButton",
			"type" : "button",
			"x":220,
			"y":20,
			"default_image" : "kowal/battlepass_1.png",
			"over_image" : "kowal/battlepass_2.png",
			"down_image" : "kowal/battlepass_3.png",
		},
		{
			"name" : "EventCalendarButton",
			"type" : "button",
			"x":149,
			"y":20,
			"default_image" : "kowal/kalendarz_1.png",
			"over_image" : "kowal/kalendarz_2.png",
			"down_image" : "kowal/kalendarz_3.png",
		},
		{
			"name" : "VoiceChatButton",
			"type" : "button",
			"x":78,
			"y":20,
			"default_image" : "kowal/voicechat_1.png",
			"over_image" : "kowal/voicechat_2.png",
			"down_image" : "kowal/voicechat_3.png",
		},
	),
}
