# -*- coding: iso-8859-1 -*-
import uiScriptLocale

PATH = "Assets/kowal/itemshop/"

window = {
    "name": "ItemShopDialog",
    "style": (
        "movable",
        "float",
    ),
    "x": 0,
    "y": 0,
    "width": 792,
    "height": 584,
    "children": (
        {
            "name": "Board",
            "type": "image",
            "style": ("attach",),
            "x": 0,
            "y": 0,
            "width": 792,
            "height": 584,
            "image": PATH + "BG.png",
            "children": (
                ## Logo top-left
                {
                    "name": "Logo",
                    "type": "button",
                    "x": 35,
                    "y": 2,
                    "default_image": PATH + "logo.png",
                    "over_image": PATH + "logo.png",
                    "down_image": PATH + "logo.png",
                },
                ## SM balance display
                {
                    "name": "stankonta",
                    "type": "image",
                    "x": 200,
                    "y": 22,
                    "image": PATH + "sm_value.png",
                    "children": (
                        {
                            "name": "money_value",
                            "type": "text",
                            "x": 0,
                            "y": -12,
                            "all_align": "center",
                            "fontname": "Tahoma:12b",
                            "outline": True,
                            "text": "0 SM",
                        },
                    ),
                },
                ## Top-right buttons
                {
                    "name": "doladuj_button",
                    "type": "button",
                    "x": 510,
                    "y": 15,
                    "default_image": PATH + "doladuj_btn0.png",
                    "over_image": PATH + "doladuj_btn1.png",
                    "down_image": PATH + "doladuj_btn2.png",
                },
                {
                    "name": "VoucherButton",
                    "type": "button",
                    "x": 605,
                    "y": 15,
                    "default_image": PATH + "voucher_btn0.png",
                    "over_image": PATH + "voucher_btn1.png",
                    "down_image": PATH + "voucher_btn2.png",
                },
                {
                    "name": "wheel_button",
                    "type": "button",
                    "x": 670,
                    "y": 1,
                    "default_image": PATH + "kololosu_btn0.png",
                    "over_image": PATH + "kololosu_btn1.png",
                    "down_image": PATH + "kololosu_btn2.png",
                },
                {
                    "name": "ExitButton",
                    "type": "button",
                    "x": 750,
                    "y": 5,
                    "default_image": PATH + "exit_btn0.png",
                    "over_image": PATH + "exit_btn1.png",
                    "down_image": PATH + "exit_btn2.png",
                },
                ## Main content area
                {
                    "name": "all_window",
                    "type": "window",
                    "x": 0,
                    "y": 100,
                    "width": 792,
                    "height": 475,
                    "children": (
                        ## Left panel - categories
                        {
                            "name": "categories_board",
                            "type": "window",
                            "x": 18,
                            "y": 10,
                            "width": 212,
                            "height": 460,
                            "children": (
                                {
                                    "name": "discount_button",
                                    "type": "radio_button",
                                    "x": 0,
                                    "y": 0,
                                    "default_image": PATH + "category_btn0.png",
                                    "over_image": PATH + "category_btn1.png",
                                    "down_image": PATH + "category_btn2.png",
                                },
                            ),
                        },
                        ## Right panel - items
                        {
                            "name": "items_board",
                            "type": "window",
                            "x": 290,
                            "y": 10,
                            "width": 480,
                            "height": 460,
                            "children": (
                                {
                                    "name": "no_discount_items_text",
                                    "type": "text",
                                    "x": 0,
                                    "y": 0,
                                    "all_align": "center",
                                    "fontname": "Tahoma:14b",
                                    "outline": True,
                                    "text": uiScriptLocale.ITEMSHOP_NO_DISCOUNT_ITEMS,
                                },
                            ),
                        },
                    ),
                },
                ## Wheel window (koło losu)
                {
                    "name": "wheel_window",
                    "type": "window",
                    "x": 0,
                    "y": 100,
                    "width": 792,
                    "height": 475,
                    "children": (
                        {
                            "name": "wheel_category_list_bg",
                            "type": "window",
                            "x": 18,
                            "y": 10,
                            "width": 212,
                            "height": 460,
                        },
                        {
                            "name": "wheel_item_list_bg",
                            "type": "window",
                            "x": 590,
                            "y": 10,
                            "width": 180,
                            "height": 460,
                        },
                        {
                            "name": "wheel_bg",
                            "type": "image",
                            "x": 265,
                            "y": -5,
                            "image": PATH + "kololosu_bg.png",
                            "children": (
                                {
                                    "name": "wheel_animation_image",
                                    "type": "image",
                                    "x": 83,
                                    "y": 63,
                                    "image": "d:/ymir work/ui/itemshop/wheel/1.tga",
                                },
                                {
                                    "name": "wheel_item_slot",
                                    "type": "slot",
                                    "x": 65,
                                    "y": 28,
                                    "width": 329,
                                    "height": 329,
                                    "slot": (
                                        {"index": 0, "x": 161, "y": 53, "width": 32, "height": 32},
                                        {"index": 1, "x": 207, "y": 63, "width": 32, "height": 32},
                                        {"index": 2, "x": 248, "y": 93, "width": 32, "height": 32},
                                        {"index": 3, "x": 277, "y": 135, "width": 32, "height": 32},
                                        {"index": 4, "x": 290, "y": 182, "width": 32, "height": 32},
                                        {"index": 5, "x": 277, "y": 228, "width": 32, "height": 32},
                                        {"index": 6, "x": 248, "y": 271, "width": 32, "height": 32},
                                        {"index": 7, "x": 207, "y": 298, "width": 32, "height": 32},
                                        {"index": 8, "x": 160, "y": 307, "width": 32, "height": 32},
                                        {"index": 9, "x": 116, "y": 296, "width": 32, "height": 32},
                                        {"index": 10, "x": 72, "y": 269, "width": 32, "height": 32},
                                        {"index": 11, "x": 44, "y": 229, "width": 32, "height": 32},
                                        {"index": 12, "x": 30, "y": 183, "width": 32, "height": 32},
                                        {"index": 13, "x": 41, "y": 133, "width": 32, "height": 32},
                                        {"index": 14, "x": 70, "y": 92, "width": 32, "height": 32},
                                        {"index": 15, "x": 112, "y": 63, "width": 32, "height": 32},
                                    ),
                                },
                                {
                                    "name": "wheel_start_button",
                                    "type": "button",
                                    "x": (513 - 117) / 2 - 10,
                                    "y": (481 - 120) / 2 - 10,
                                    "default_image": PATH + "kololosu_play_btn0.png",
                                    "over_image": PATH + "kololosu_play_btn1.png",
                                    "down_image": PATH + "kololosu_play_btn2.png",
                                    "children": (
                                        {
                                            "name": "wheel_start_text",
                                            "type": "text",
                                            "x": 0,
                                            "y": 0,
                                            "all_align": "center",
                                            "text": uiScriptLocale.ITEMSHOP_BTN_SPIN,
                                            "fontname": "Tahoma:14b",
                                            "color": 0xFFFFD700,
                                            "outline": 1,
                                        },
                                    ),
                                },
                            ),
                        },
                        {
                            "name": "wheel_auto_button",
                            "type": "toggle_button",
                            "x": 30,
                            "y": 420,
                            "default_image": PATH + "category_btn0.png",
                            "over_image": PATH + "category_btn1.png",
                            "down_image": PATH + "category_btn2.png",
                            "text": "",
                            "children": (
                                {
                                    "name": "wheel_auto_button_text_01",
                                    "type": "text",
                                    "x": 0,
                                    "y": 0,
                                    "all_align": "center",
                                    "fontname": "Tahoma:12",
                                    "outline": True,
                                    "text": uiScriptLocale.AUTOMATIC_SPINNING,
                                },
                            ),
                        },
                        {
                            "name": "wheel_main_prize_label",
                            "type": "text",
                            "x": 139,
                            "y": 322,
                            "text_horizontal_align": "center",
                            "fontname": "Tahoma:12",
                            "outline": True,
                            "not_pick": True,
                            "text": "",
                        },
                        {
                            "name": "wheel_main_prize_slot",
                            "type": "slot",
                            "x": 123,
                            "y": 340,
                            "width": 32,
                            "height": 32,
                            "slot": (
                                {"index": 0, "x": 0, "y": 0, "width": 32, "height": 32},
                            ),
                        },
                        {
                            "name": "wheel_price_bg",
                            "type": "image",
                            "x": 68,
                            "y": 380,
                            "image": PATH + "item_price_bg.png",
                            "children": (
                                {
                                    "name": "wheel_price_value",
                                    "type": "text",
                                    "x": 0,
                                    "y": 0,
                                    "fontname": "Tahoma:12",
                                    "outline": True,
                                    "all_align": "center",
                                    "text": "",
                                },
                            ),
                        },
                    ),
                },
                ## Promo/Voucher window
                {
                    "name": "promo_window",
                    "type": "window",
                    "x": 290,
                    "y": 100,
                    "width": 480,
                    "height": 475,
                    "children": (
                        {
                            "name": "voucher_bg_image",
                            "type": "image",
                            "x": 16,
                            "y": 35,
                            "image": PATH + "voucher_bg.png",
                            "children": (
                                {
                                    "name": "CodeFrameSlotText",
                                    "type": "editline",
                                    "x": 145,
                                    "y": 132,
                                    "width": 194,
                                    "height": 17,
                                    "input_limit": 24,
                                    "secret_flag": 0,
                                    "text": "",
                                },
                                {
                                    "name": "voucher_title_text",
                                    "type": "text",
                                    "x": 224,
                                    "y": 55,
                                    "text": uiScriptLocale.ITEMSHOP_VOUCHER_TITLE,
                                    "text_horizontal_align": "center",
                                    "fontname": "Tahoma:20b",
                                    "outline": 1,
                                    "color": 0xFFFFD700,
                                },
                                {
                                    "name": "voucher_info_text1",
                                    "type": "text",
                                    "x": 224,
                                    "y": 255,
                                    "text": uiScriptLocale.ITEMSHOP_VOUCHER_INFO_1,
                                    "text_horizontal_align": "center",
                                    "outline": 1,
                                    "color": 0xFFFFD700,
                                },
                                {
                                    "name": "voucher_info_text2",
                                    "type": "text",
                                    "x": 224,
                                    "y": 270,
                                    "text": uiScriptLocale.ITEMSHOP_VOUCHER_INFO_2,
                                    "text_horizontal_align": "center",
                                    "outline": 1,
                                    "color": 0xFFFFD700,
                                },
                                {
                                    "name": "promo_btn",
                                    "type": "button",
                                    "x": (448 - 142) / 2,
                                    "y": 160,
                                    "default_image": PATH + "button_voucher0.png",
                                    "over_image": PATH + "button_voucher1.png",
                                    "down_image": PATH + "button_voucher2.png",
                                    "children": (
                                        {
                                            "name": "promo_btn_text",
                                            "type": "text",
                                            "x": 0,
                                            "y": 0,
                                            "all_align": "center",
                                            "text": uiScriptLocale.ITEMSHOP_BTN_CONFIRM,
                                            "fontname": "Tahoma:12",
                                            "outline": 1,
                                        },
                                    ),
                                },
                            ),
                        },
                    ),
                },
                ## Loading animation
                {
                    "name": "item_loading",
                    "type": "ani_image",
                    "x": (792 - 16) / 2,
                    "y": (584 - 16) / 2,
                    "delay": 6,
                    "images": (
                        "d:/ymir work/ui/loading_ani/00.tga",
                        "d:/ymir work/ui/loading_ani/01.tga",
                        "d:/ymir work/ui/loading_ani/02.tga",
                        "d:/ymir work/ui/loading_ani/03.tga",
                        "d:/ymir work/ui/loading_ani/04.tga",
                        "d:/ymir work/ui/loading_ani/05.tga",
                        "d:/ymir work/ui/loading_ani/06.tga",
                        "d:/ymir work/ui/loading_ani/07.tga",
                    ),
                },
            ),
        },
    ),
}
