import uiScriptLocale
import localeInfo

BOARD_WIDTH = 330
BOARD_HEIGHT = 160

window = {
	"name" : "OfflineShopInputDialog",
	"x" : 0,"y" : 0,
	"style" : ("movable", "float",),
	"width" : BOARD_WIDTH,"height" : BOARD_HEIGHT,
	"children" :
	(
        {
            "name" : "board",
            "type" : "board",
            "x": 0, "y": 0,
            "width": BOARD_WIDTH,"height": BOARD_HEIGHT,
            "children" :
            (
				{
					"name" : "TitleBar",
					"type" : "titlebar",
					"style" : ("attach",),
					"x" : 8,"y" : 7,
					"width" : BOARD_WIDTH-15,
					"color" : "yellow",
					"children" :
					(
						{ 
							"name": "TitleName",
							"type":"text",
							"x":BOARD_WIDTH/2,"y":0,
							"outline":1,
							"text": uiScriptLocale.OFFLINE_SHOP_EDIT_WINDOW,
							"text_horizontal_align":"center",
						},
					),
				},
				{
					"name" : "Header",
					"type" : "image",
					"x": 38, "y": 35,
					"image" : "d:/ymir work/ui/offline_shop/test_image_020.tga",
					"children" :
					(
						{
							"name" : "TimeName",
							"type" : "text",
							"x" : 93,"y" : 0,
							"text" : localeInfo.OFFLINE_SHOP_CTIME,
							"outline":"1",
						},
					),
				},
                {
                  	"name" : "separator",
					"type" : "image",
					# "x": 35, "y": 80,
					"x": 59, "y": 90,
					"image" : "d:/ymir work/ui/offline_shop/separator.tga",  
				},
                {
                    "name" : "ThinBoard",
                    "type" : "thinboard_new",
                    "x": 8, "y": 58,
                    "width":312,"height":50,
				},
				{
					"name" : "1Hour",
					"type" : "radio_button",
					"x" : 30,"y" : 73,
					"tooltip_text_new" : "1 hod.",
					"tooltip_text_color" : 0xfff1e6c0,
					"tooltip_x" : 0,
					"tooltip_y" : -35,
					"default_image" : "d:/ymir work/ui/offline_shop/button_example_260.tga",
					"over_image" : "d:/ymir work/ui/offline_shop/button_example_261.tga",
					"down_image" : "d:/ymir work/ui/offline_shop/button_example_262.tga",
				},
				{
					"name" : "3Hours",
					"type" : "radio_button",
					"x" : 70,"y" : 73,
					"tooltip_text_new" : "3 hod.",
					"tooltip_text_color" : 0xfff1e6c0,
					"tooltip_x" : 0,
					"tooltip_y" : -35,
					"default_image" : "d:/ymir work/ui/offline_shop/button_example_260.tga",
					"over_image" : "d:/ymir work/ui/offline_shop/button_example_261.tga",
					"down_image" : "d:/ymir work/ui/offline_shop/button_example_262.tga",
				},
				{
					"name" : "8Hours",
					"type" : "radio_button",
					"x" : 110,"y" : 73,
					"tooltip_text_new" : "8 hod.",
					"tooltip_text_color" : 0xfff1e6c0,
					"tooltip_x" : 0,
					"tooltip_y" : -35,
					"default_image" : "d:/ymir work/ui/offline_shop/button_example_260.tga",
					"over_image" : "d:/ymir work/ui/offline_shop/button_example_261.tga",
					"down_image" : "d:/ymir work/ui/offline_shop/button_example_262.tga",
				},
				{
					"name" : "12Hours",
					"type" : "radio_button",
					"x" : 155,"y" : 73,
					"tooltip_text_new" : "12 hod.",
					"tooltip_text_color" : 0xfff1e6c0,
					"tooltip_x" : 0,
					"tooltip_y" : -35,
					"default_image" : "d:/ymir work/ui/offline_shop/button_example_260.tga",
					"over_image" : "d:/ymir work/ui/offline_shop/button_example_261.tga",
					"down_image" : "d:/ymir work/ui/offline_shop/button_example_262.tga",
				},
				{
					"name" : "24Hours",
					"type" : "radio_button",
					"x" : 195,"y" : 73,
					"tooltip_text_new" : "24 hod.",
					"tooltip_text_color" : 0xfff1e6c0,
					"tooltip_x" : 0,
					"tooltip_y" : -35,
					"default_image" : "d:/ymir work/ui/offline_shop/button_example_260.tga",
					"over_image" : "d:/ymir work/ui/offline_shop/button_example_261.tga",
					"down_image" : "d:/ymir work/ui/offline_shop/button_example_262.tga",
				},
				{
					"name" : "48Hours",
					"type" : "radio_button",
					"x" : 235,"y" : 73,
					"tooltip_text_new" : "48 hod.",
					"tooltip_text_color" : 0xfff1e6c0,
					"tooltip_x" : 0,
					"tooltip_y" : -35,
					"default_image" : "d:/ymir work/ui/offline_shop/button_example_260.tga",
					"over_image" : "d:/ymir work/ui/offline_shop/button_example_261.tga",
					"down_image" : "d:/ymir work/ui/offline_shop/button_example_262.tga",
				},
				{
					"name" : "72Hours",
					"type" : "radio_button",
					"x" : 275,"y" : 73,
					"tooltip_text_new" : "72 hod.",
					"tooltip_text_color" : 0xfff1e6c0,
					"tooltip_x" : 0,
					"tooltip_y" : -35,
					"default_image" : "d:/ymir work/ui/offline_shop/button_example_260.tga",
					"over_image" : "d:/ymir work/ui/offline_shop/button_example_261.tga",
					"down_image" : "d:/ymir work/ui/offline_shop/button_example_262.tga",
				},
				{
					"name" : "AgreeButton",
					"type" : "button",
					"x" : -50,
					"y" : 55,
					"horizontal_align" : "center",
					"vertical_align" : "center",
					"default_image" : uiScriptLocale.LOCALE_OFFLINESHOP_PATH + "/accept_01.tga",
					"over_image" : uiScriptLocale.LOCALE_OFFLINESHOP_PATH + "/accept_02.tga",
					"down_image" : uiScriptLocale.LOCALE_OFFLINESHOP_PATH + "/accept_03.tga",
				},
				{
					"name" : "CancelButton",
					"type" : "button",
					"x" : 50,
					"y" : 55,
					"horizontal_align" : "center",
					"vertical_align" : "center",
					"default_image" : uiScriptLocale.LOCALE_OFFLINESHOP_PATH + "/no_01.tga",
					"over_image" : uiScriptLocale.LOCALE_OFFLINESHOP_PATH + "/no_02.tga",
					"down_image" : uiScriptLocale.LOCALE_OFFLINESHOP_PATH + "/no_03.tga",
				},			
			),
		},
	),
}